#:kivy 1.8.0
#:import sep os.sep

<ShowcaseScreen>:
    ScrollView:
        do_scroll_x: False
        do_scroll_y: False if root.fullscreen else (content.height > root.height - dp(16))
        AnchorLayout:
            size_hint_y: None
            height: root.height if root.fullscreen else max(root.height, content.height)
            GridLayout:
                id: content
                cols: 1

#===============================================================================
# FILECHOOSER
#===============================================================================

<PathLabel@Label>:
    size_hint_x: .93
    text_size: (self.size[0] - 20, self.size[1])
    shorten: True
    text: app.home_path
    shorten_from: "left"
    halign: "left"
    valign: "middle"
    canvas.before:
        Color:
            rgba: .35, .35, .35, 1
        Rectangle:
            pos: self.pos
            size: self.size

<PathText@TextInput>:
    size_hint_x: .93
    multiline: False
    text: app.home_path

#===============================================================================
# MOUSE OVER
#===============================================================================

<MouseOverLabel@Button>:
    text_size: self.size
    halign: "center"
    valign: "middle"
    background_down: "atlas://data/images/defaulttheme/button"

<SideLabel>:
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            source: "data/backgrounds/side_label.png"
            pos: self.pos
            size: self.size

#===============================================================================
# TAXA/FILE INFORMATIVE POPUPS
#===============================================================================

<PopupLabel@Label>:
    bold: True
    halign: "left"
    valign: "middle"
    text_size: self.size
    size_hint_x: .6

<PopupText@TextInput>:
    multiline: False
    readonly: True
    size_hint_x: .4

<PopupBox@BoxLayout>:
    size_hint_y: None
    height: 30
    spacing: 10

<FilePopup@BoxLayout>
    orientation: "vertical"
    padding: 10
    spacing: 5
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        PopupBox:
            PopupLabel:
                text: "Input format:"
            PopupText:
                id: in_format
        PopupBox:
            PopupLabel:
                text: "Sequence type:"
            PopupText:
                id: seq_type
        PopupBox:
            PopupLabel:
                text: "Alignment:"
            PopupText:
                id: is_aln
        PopupBox:
            PopupLabel:
                text: "Sequence size:"
            PopupText:
                id: seq_size
        PopupBox:
            PopupLabel:
                text: "Number of taxa:"
            PopupText:
                id: n_taxa
        Widget
    Button:
        size_hint_y: None
        height: 30
        text: "Cancel"
        on_release:
            root.cancel()

<TaxaPopup>
    orientation: "vertical"
    size_hint_y: None
    padding: 15
    spacing: 5
    PopupLabel:
        background_color: (.7, .7, .7)
        id: dataset_label
        halign: "center"
        size_hint_x: 1
        size_hint_y: None
        height: 30
        canvas.before:
            Color:
                rgba: .35, .35, .35, 1
            Rectangle:
                pos: self.pos
                size: self.size
    PopupBox:
        PopupLabel:
            #size_hint_x: .45
            text: "Sequence length:"
        PopupText:
            #size_hint_x: .55
            id: seq_len
    PopupBox:
        PopupLabel:
            #size_hint_x: .45
            text: "Number of indels:"
        PopupText:
            #size_hint_x: .55
            id: indels
    PopupBox:
        PopupLabel:
            #size_hint_x: .65
            text: "Number of missing data:"
        PopupText:
            #size_hint_x: .35
            id: missing
    PopupBox:
        PopupLabel:
            #size_hint_x: .7
            text: "Effective sequence length:"
        PopupText:
            #size_hint_x: .3
            id: ef_seq_len
    PopupBox:
        PopupLabel:
            #size_hint_x: .35
            text: "File coverage"
        PopupText:
            #size_hint_x: .65
            id: file_cov

#===============================================================================
# CHECK ACTIONS
#===============================================================================

<CheckBt@Button>:
    background_normal: "data/backgrounds/bt_process.png"
    bold: True
    shorten: True
    shorten_from: "right"
    text_size: self.size
    halign: "center"
    valign: "middle"


<CheckDialog@BoxLayout>:
    orientation: "vertical"
    id: check
    text: None
    BoxLayout:
        padding: 10
        Label:
            canvas.before:
                Color:
                    rgba: (.2, .2, .2, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size
            valign: "middle"
            halign: "center"
            text_size: (self.size[0] - 5, self.size[1])
            id: check_text
    BoxLayout:
        size_hint_y: None
        height: 50
        spacing: 10
        padding: 10
        CheckBt:
            background_normal: "data/backgrounds/check_ok.png"
            background_down: "data/backgrounds/check_cancel.png"
            size_hint_x: 1
            text: "Yes"
            id: check_ok
            on_release:
                root.cancel()
        Button:
            id: check_cancel
            background_normal: "data/backgrounds/check_cancel.png"
            background_down: "data/backgrounds/check_ok.png"
            bold: True
            text: "No"
            on_release:
                root.cancel()

#===============================================================================
# WARNINGS
#===============================================================================

<WarningDialog@BoxLayout>:
    padding: 10
    orientation: "vertical"
    BoxLayout:
        padding: 10
        Label:
            id: warning_l
            halign: "center"
            valign: "middle"
            text_size: self.size
            markup: True
            canvas.before:
                Color:
                    rgba: (.2, .2, .2, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size
    BoxLayout:
        size_hint_y: None
        height: 60
        padding: 10
        Widget:
            size_hint_x: .7
        Button:
            background_normal: "data/backgrounds/check_ok.png"
            background_down: "data/backgrounds/check_cancel.png"
            text: "Close"
            on_release:
                root.cancel()
        Widget:
            size_hint_x: .7

#===============================================================================
# TAXA GROUP CREATION
#===============================================================================

<TaxaGroupDialog@BoxLayout>:
    orientation: "vertical"
    padding: 10
    spacing: 10
    BoxLayout:
        size_hint_y: .1
        BoxLayout:
            spacing: 10
            Label:
                text: "Set group name:"
                bold: True
                size_hint_x: .2
                text_size: self.size
                halign: "left"
                valign: "middle"
            TextInput:
                size_hint_x: .8
                id: group_name
                text: "untitled_1"
                multiline: False

    BoxLayout:
        BoxLayout:
            orientation: "vertical"
            Label:
                canvas.before:
                    Color:
                        rgba: .2, .2, .2, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: "Selected taxa"
                size_hint_y: None
                height: 40
                bold: True
            Hseparator
            ScrollView:
                bar_width: 10
                scroll_type: ["bars", "content"]
                canvas.before:
                    Color:
                        rgba: .3, .3, .3, .5
                    Rectangle:
                        pos: self.pos
                        size: self.size
                GridLayout:
                    id: select_grid
                    cols:1
                    size_hint_y: None
                    height: 0
            Widget:
                size_hint_y: None
                height: 15
            Button:
                background_normal: "data/backgrounds/bt_process.png"
                size_hint_y: .15
                font_size: 18
                text: "Save"
                bold: True
                on_release:
                    if root.ids.group_name.text not in app.taxa_groups: app.save_taxa_group(root.ids.select_grid, root.ids.group_name.text); root.cancel()
        BoxLayout:
            orientation: "vertical"
            size_hint_x: .30
            spacing: 10
            BoxLayout:
                padding: 20
                spacing: 20
                orientation: "vertical"
                Button:
                    background_down: "data/backgrounds/tg_addall.png"
                    background_normal: "data/backgrounds/tg_addall_down.png"
                    size_hint: (None, None)
                    size: (47,50)
                    border: (0,0,0,0)
                    on_release:
                        app.taxagroup_move_taxa(root.ids.all_grid, root.ids.select_grid, True)
                Button:
                    background_down: "data/backgrounds/tg_add.png"
                    background_normal: "data/backgrounds/tg_add_down.png"
                    size_hint: (None, None)
                    size: (47,50)
                    on_release:
                        app.taxagroup_move_taxa(root.ids.all_grid, root.ids.select_grid, False)
                Button:
                    background_down: "data/backgrounds/tg_remove.png"
                    background_normal: "data/backgrounds/tg_remove_down.png"
                    size_hint: (None, None)
                    size: (47,50)
                    on_release:
                        app.taxagroup_move_taxa(root.ids.select_grid, root.ids.all_grid, False)
                Button:
                    background_down: "data/backgrounds/tg_removeall.png"
                    background_normal: "data/backgrounds/tg_removeall_down.png"
                    size_hint: (None, None)
                    size: (47,50)
                    on_release:
                        app.taxagroup_move_taxa(root.ids.select_grid, root.ids.all_grid, True)
            Widget:
                size_hint_y: .15
        BoxLayout:
            orientation: "vertical"
            Label:
                canvas.before:
                    Color:
                        rgba: .2, .2, .2, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: "All taxa"
                size_hint_y: None
                height: 40
                bold: True
            Hseparator
            ScrollView:
                bar_width: 10
                scroll_type: ["bars", "content"]
                canvas.before:
                    Color:
                        rgba: .3, .3, .3, .5
                    Rectangle:
                        pos: self.pos
                        size: self.size
                GridLayout:
                    id: all_grid
                    cols:1
                    size_hint_y: None
                    height: 0
            Widget:
                size_hint_y: None
                height: 15
            Button:
                background_normal: "data/backgrounds/bt_process_off.png"
                size_hint_y: .15
                font_size: 18
                text: "Cancel"
                bold: True
                on_release:
                    root.cancel()

#===============================================================================
# GENERAL SAVE FILE
#===============================================================================

<SaveDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        spacing: 10

        FileChooserListView:
            id: sd_filechooser
            text: "master"
            on_selection: text_input.text = self.selection

        BoxLayout:
            id: txt_box
            orientation: "horizontal"
            size_hint_y: None
            height: 30
            Label:
                size_hint_x: None
                width: 100
                text: "File name:"
            TextInput:
                id: text_input
                multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30

            Button:
                text: "Save"
                on_release:
                    if sd_filechooser.text == "main_output" and txt_box.height == 30: app.save_file(sd_filechooser.path, file_name = text_input.text, idx = sd_filechooser.text)
                    if sd_filechooser.text == "main_output" and txt_box.height == 0: app.save_file(sd_filechooser.path, idx = sd_filechooser.text)
                    if sd_filechooser.text == "export": app.export_names(sd_filechooser.path, file_name = text_input.text)
                    root.cancel()

            Button:
                text: "Cancel"
                on_release: root.cancel()

#===============================================================================
# ACTION BAR HEADERS
#===============================================================================

<MainHeader@ActionToggleButton>:
    size_hint_x: 1
    font_size: 20
    bold: True
    group: "main_header"
    disabled_color: (1, 1, 1, 1)

#===============================================================================
# SIDE PANEL WIDGETS
#===============================================================================

<SelectionBox@BoxLayout>:
    orientation: "horizontal"
    size_hint_y: None
    height: 35
    spacing: 20
    Button:
        text: "Select All"
        disabled: True
    Button:
        text: "Deselect All"
        disabled: True

<SideButton@ToggleButton>:
    group: "side_buttons"
    size_hint_y: .1
    font_size: 30
    bold: True
    disabled_color: (1,1,1,1)
    border: (0,0,0,0)

#===============================================================================
#                               PROCESS SCREEN
#===============================================================================

#===============================================================================
# PROCESS PARTITIONS
#===============================================================================

<PartitionBt@ToggleButton>:
    size_hint_y: None
    height: 60
    size_hint_x: .9
    background_normal: "data/backgrounds/partitions_normal.png"
    background_disabled_normal: "data/backgrounds/partitions_normal.png"
    background_down: "data/backgrounds/partitions_down.png"
    background_disabled_down: "data/backgrounds/partitions_down.png"
    text_size: [self.size[0]*.9, self.size[1]]
    disabled_color: (1,1,1,1)
    shorten: True
    shorten_from: "right"
    haligh: "left"
    valign: "middle"

<DetailLabel@Label>:
    size_hint_y: None
    height: 30
    halign: "left"
    valign: "middle"
    text_size: self.size
    markup: True

<FieldLabel@Label>:
    size_hint_y: None
    height: 30
    bold: True
    halign: "left"
    valign: "top"
    text_size: self.size
    color: (0.216, 0.67, 0.784, 1)

<PartitionScreen@BoxLayout>:
    orientation: "vertical"
    Label:
        size_hint_y: None
        height: 30

    BoxLayout:
        padding: 10
        orientation: "vertical"
        spacing: 10
        canvas.before:
            Color:
                rgba: (1,1,1,1)
            Rectangle:
                source: "data/backgrounds/partition_content.png"
                pos: self.pos
                size: self.size

        BoxLayout:
            canvas.before:
                Color:
                    rgba: (1,1,1,1)
                Rectangle:
                    source: "data/backgrounds/partition_file_background.png"
                    pos: self.pos
                    size: self.size
            size_hint_y: .5
            orientation: "vertical"
            padding: 10
            FieldLabel:
                text: "Files"
            ScrollView:
                GridLayout:
                    cols: 1
                    spacing: (5,5)
                    id: file_content

        Hseparator:
            thickness: 1.5

        BoxLayout:
            spacing: 10
            size_hint_y: .5
            BoxLayout:
                canvas.before:
                    Color:
                        rgba: (1,1,1,1)
                    Rectangle:
                        source: "data/backgrounds/partition_file_background.png"
                        pos: self.pos
                        size: self.size
                orientation: "vertical"
                padding: 10
                FieldLabel:
                    text: "Partition Details"
                BoxLayout:
                    orientation: "vertical"
                    DetailLabel:
                        id: size_d
                    DetailLabel:
                        id: seq_typ
                    DetailLabel:
                        id: files_d
                    Widget

            Vseparator

            BoxLayout:
                orientation: "vertical"
                canvas.before:
                    Color:
                        rgba: (1,1,1,1)
                    Rectangle:
                        source: "data/backgrounds/partition_file_background.png"
                        pos: self.pos
                        size: self.size
                FieldLabel:
                    text: "Substitution model"
                    size_hint_y: None
                    halign: "center"
                    valign: "middle"
                    height: 30
                BoxLayout:
                    orientation: "vertical"
                    size_hint_y: .3
                    Spinner:
                        canvas.before:
                        text: "None"
                        bold: True
                        values: ("GTR", "SYM", "HKY", "K2P", "F81", "JC")
                BoxLayout:
                    size_hint_y: .3
                    Label:
                        text: "Unlink"
                    CheckBox
                BoxLayout:
                    orientation: "vertical"
                    size_hint_y: .7
                    BoxLayout:
                        ToggleButton:
                            id: codon_0
                            text: "1st"
                        Button:
                            size_hint_x: .2
                    BoxLayout:
                        ToggleButton:
                            id: codon_1
                            text: "2nd"
                        Button:
                            size_hint_x: .2
                    BoxLayout:
                        ToggleButton:
                            id: codon_2
                            text: "3rd"
                        Button:
                            size_hint_x: .2


<PartitionsDialog>:
    padding: 10
    spacing: 10
    orientation: "vertical"
    BoxLayout:
        size_hint_y: None
        height: 30
        canvas.before:
            Color:
                rgba: (1,1,1,1)
            Rectangle:
                source: "data/backgrounds/partition_topbar.png"
                pos: self.pos
                size: self.size

    BoxLayout:
        spacing: 10
        BoxLayout:
            orientation: "vertical"
            size_hint_x: None
            width: 300
            spacing: 5
            BoxLayout:
                spacing: 5
                size_hint_y: None
                height: 30
                CheckBox:
                    size_hint_x: .1
                Label:
                    size_hint_x: .9
                    text: "Partitions"
                    bold: True

            Hseparator:
                thickness: 1.1

            ScrollView:
                size_hint_y: .9
                bar_inactive_color: (0,0,0,0)
                GridLayout:
                    size_hint_y: None
                    height: 0
                    cols: 2
                    id: gl_content

        Carousel:
            id: partitions_car
            anim_move_duration: 0

    Widget:
        size_hint_y: None
        height: 10

    BoxLayout:
        size_hint_y: None
        height: 30
        Widget:
            size_hint_x: .3
        BoxLayout:
            spacing: 10
            Button:
                text: "OK"
            Button:
                text: "Close"
                on_release:
                    root.cancel()
        Widget:
            size_hint_x: .3



#===============================================================================
# PROCESS OUTPUT FORMAT
#===============================================================================

<SettingsBt@Button>:
    size_hint_x: .2
    disabled: True
    Image:
        source: "data/backgrounds/settings.png"
        pos: self.parent.x + 8, self.parent.y + 8
        #x: self.parent.x
        size: 18, 18
        allow_stretch: True

<FormatDialog>:
    padding: [30, 20, 30, 20]
    spacing: 10
    orientation: "vertical"
    id: format_dlg
    BoxLayout:
        ToggleButton:
            id: fasta
            state: "down"
            text: "Fasta"
        SettingsBt
    BoxLayout:
        ToggleButton:
            id: phylip
            text: "Phylip"
        SettingsBt:
            disabled: False
            on_release:
                app.dialog_phylip_extra()
    BoxLayout:
        ToggleButton:
            id: nexus
            text: "Nexus"
        SettingsBt:
            disabled: False
            on_release:
                app.dialog_nexus_extra()
    BoxLayout:
        ToggleButton:
            id: mcmctree
            text: "MCMCTree"
        SettingsBt
    BoxLayout:
        ToggleButton:
            id: ima2
            text: "IMa2"
            disabled: True
        SettingsBt
    Widget
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Done"
            on_release: app.save_format(format_dlg)
        Button:
            text: "Cancel"
            on_release: root.cancel()

<NexusExtra@BoxLayout>:
    padding: 10
    spacing: 10
    orientation: "vertical"
    BoxLayout:
        Label:
            text: "Write the partitions block, if any."
        CheckBox:
            id: nexus_check
            size_hint_x: .2

    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 20
        Button:
            text: "Done"
            on_release:
                app.use_nexus_partitions = root.ids.nexus_check.active
                app.dismiss_subpopup()
        Button:
            text: "Cancel"
            on_release: root.cancel()

<PhylipExtra@BoxLayout>:
    padding: 10
    spacing: 10
    orientation: "vertical"
    BoxLayout:
        Label:
            text: "Create partition file when concatenating"
        CheckBox:
            id: part_check
            size_hint_x: .2

    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 20
        Button:
            text: "Done"
            on_release:
                app.create_partfile = root.ids.part_check.active
                app.dismiss_subpopup()
        Button:
            text: "Cancel"
            on_release: root.cancel()

#===============================================================================
# PROCESS FORMATTING ADDITIONAL OPTIONS
#===============================================================================

<ZorroDialog>:
    orientation: "vertical"
    padding: 10
    spacing: 15
    Switch:
        id: zorro_switch
    BoxLayout:
        spacing: 10
        size_hint_y: None
        height: 30
        Label:
            valign: "middle"
            halign: "left"
            text_size: self.size
            size_hint_x: .5
            text: "ZORRO files suffix:"
            bold: True
        TextInput:
            id: zorro_txt
            multiline: False
            size_hint_x: .5

    BoxLayout:
        orientation: "horizontal"
        spacing: 10
        Button:
            text: "Done"
            on_release: app.save_zorro_settings(zorro_txt.text)
        Button:
            text: "Cancel"
            on_release: root.cancel()

#===============================================================================
# PROCESS HAPLOTYPE ADDITIONAL OPTIONS
#===============================================================================

<TextDialog>:
    orientation: "vertical"
    padding: 10
    spacing: 10
    TextInput:
        id: txt_dlg
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Done"
            on_release:
                app.save_hap_prefix(txt_dlg)
                root.cancel()
        Button:
            text: "Cancel"
            on_release: root.cancel()

#===============================================================================
# REVERSE CONCATENATION OPTIONS
#===============================================================================

<InputList@BoxLayout>:
    orientation: "vertical"
    spacing: 10
    padding: 10
    ScrollView:
        GridLayout:
            spacing: 5
            cols: 1
            id: rev_inlist
            size_hint_y: None
            height: 0

<LoadDialog>
    orientation: "vertical"
    spacing: 10
    padding: 10
    Label:
        size_hint_y: None
        text: ld_filechooser.path
        height: 30
        text_size: (self.size[0] - 20, self.size[1])
        shorten: True
        shorten_from: "left"
        halign: "center"
        valign: "middle"
        canvas.before:
            Color:
                rgba: .35, .35, .35, 1
            Rectangle:
                pos: self.pos
                size: self.size

    FileChooserM:
        id: ld_filechooser
        f: "/*"
        filters: [self.path+self.f]
        filter_dirs: True

    BoxLayout:
        size_hint_y: None
        height: 30
        spacing: 5

        Label:
            canvas.before:
                Color:
                    rgba: (.2,.2,.2,1)
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint_x: .15
            text: "Find:"
            bold: True
        ToggleButton:
            id: case_bt
            text: "Aa"
            bold:True
            size_hint_x: .1
            state: "down"

        TextInput:
            id: text_filter
            multiline: False
            focus: True
            on_text:
                if case_bt.state == "down": ld_filechooser.f = "*"+"".join(["["+x.upper()+x.lower()+"]" for x in self.text])+"*"
                if case_bt.state == "normal": ld_filechooser.f = "*"+self.text+"*"

            on_text_validate:
                focus = True

    BoxLayout:
        size_hint_y: None
        height: 35
        spacing: 10

        Button:
            id: part_bt
            text: "OK"
            on_release:
                app.partitions_file = ld_filechooser.selection[0]
                root.cancel()

        Button:
            text: "Cancel"
            on_release: root.cancel()

<RevConcDialog>:
    orientation: "vertical"
    spacing: 10
    padding: 10

    BoxLayout:
        size_hint_y: .8
        #height: 50
        spacing: 10
        orientation: "vertical"

        DarkBox:
            height: 60
            canvas.before:
                Color:
                    rgba: (.3, .3, .3, .8)
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                size_hint_x: .7
                text: "Activate reverse concatenation"
                bold: True
                halign: "left"
                valign: "middle"
                text_size: self.size

            Switch:
                size_hint_x: .2
                id: rev_conc
                on_active:
                    if self.active == True: app.update_main_operations("reverse_concatenation"); rev_infile.disabled = False; part_file.disabled = False
                    if self.active == False: app.update_main_operations("concatenation"); rev_infile.disabled = True; part_file.disabled = True

        DarkBox:
            height: 60
            canvas.before:
                Color:
                    rgba: (.3, .3, .3, .8)
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                size_hint_x: .7
                text: "Select partition file"
                bold: True
                halign: "left"
                valign: "middle"
                text_size: self.size

            ProcessBt:
                id: part_file
                size_hint_x: .3
                text: "Select..."
                disabled: True
                on_release:
                    app.dialog_load_partfile()

        DarkBox:
            height: 60
            canvas.before:
                Color:
                    rgba: (.3, .3, .3, .8)
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                size_hint_x: .7
                text: "Select input file to reverse concatenate"
                bold: True
                halign: "left"
                valign: "middle"
                text_size: self.size

            ProcessBt:
                id: rev_infile
                size_hint_x: .3
                text: "Select..."
                disabled: True
                on_release:
                    app.dialog_reverse_inlist()

    BoxLayout:
        size_hint_y: None
        height: 35
        spacing: 10

        Button:
            id: part_bt
            text: "OK"
            on_release:
                app.save_reverseconc_settings()
                root.cancel()

        Button:
            text: "Cancel"
            on_release: root.cancel()

#===============================================================================
# PROCESS FILTER ADDITIONAL OPTIONS
#===============================================================================

<FilterDialog>:
    orientation: "vertical"
    padding: 20
    spacing: 20

    Label:
        text: "Gap threshold"
        bold: True
        halign: "left"
        valign: "middle"
        text_size: self.size

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: 30
        spacing: 20
        Slider:
            id: gap_sli
            size_hint_x: .85
            min: 0
            max: 100
            step: 1
            value: 25
        TextInput:
            size_hint_x: .15
            id: gap_ti
            text: "{}".format(round(gap_sli.value))
            multiline: False
            on_text_validate: if app.check_filters(gap_ti.text): gap_sli.value = app.check_filters(gap_ti.text)[1]

    Label:
        text: "Missing data threshold"
        bold: True
        halign: "left"
        valign: "middle"
        text_size: self.size

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: 30
        spacing: 20
        Slider:
            id: mis_sli
            size_hint_x: .85
            min: 0
            max: 100
            step: 1
            value: 50
        TextInput:
            size_hint_x: .15
            id: mis_ti
            text: "{}".format(round(mis_sli.value))
            multiline: False
            on_text_validate: if app.check_filters(mis_ti.text): mis_sli.value = app.check_filters(mis_ti.text)[1]

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: 30
        Button:
            text: "Done"
            on_release: app.save_filter(gap_sli.value, mis_sli.value)
        Button:
            text: "Cancel"
            on_release: root.cancel()

<Sidebt@ToggleButton>:
    #background_color: [0,0,0,1]
    size_hint_y: None
    height: 50
    background_normal: "data/backgrounds/main_op_bt.png"
    background_down: "data/backgrounds/bt_sideprocess.png"
    background_disabled_down: "data/backgrounds/bt_sideprocess.png"
    disabled_color: (1, 1, 1, 1)
    halign: "center"
    valign: "middle"
    text_size: self.size
    bold: True
    font_size: 18
    padding: (20, 0)

# Vertical light grey separator
<Vseparator@Widget>:
    size_hint_x: None
    width: self.thickness + 2 * self.margin
    thickness: 1
    margin: 1
    canvas:
        Color:
            rgb: .5, .5, .5
        Rectangle:
            pos: self.x + self.margin + 1, self.y + self.margin
            size: self.thickness, self.height - 2 * self.margin + 5

<LightBox@BoxLayout>:
    height: 40
    orientation: "horizontal"
    size_hint_y: None
    padding: 10
    canvas.before:
        Color:
            rgba: (.3, .3, .3, .8)
        Rectangle:
            pos: self.pos
            size: self.size

<DarkBox@BoxLayout>:
    height: 55
    orientation: "horizontal"
    size_hint_y: None
    padding: 5

<Hseparator@Widget>:
    size_hint_y: None
    height: self.thickness + 2 * self.margin
    thickness: 1
    margin: 1
    canvas:
        Color:
            rgb: .5, .5, .5
        Rectangle:
            pos: self.x + self.margin, self.y + self.margin +1
            size: self.width - 2 * self.margin, self.thickness

<ProcessBt@Button>:
    background_normal: "data/backgrounds/bt_process.png"
    size_hint_x: .2
    bold: True
    shorten: True
    shorten_from: "right"
    text_size: self.size
    halign: "center"
    valign: "middle"

#===============================================================================
# PROCESS GENERAL OPTIONS
#===============================================================================

<ProcessGeneral@GridLayout>:
    size_hint_y: None
    #height: 45 * len([x for y in [z.children for z in self.children] for x in y])
    height: (45 * len(self.children[0].children))
    cols: 1
    opacity: 0
    __safe_id: [dataset_dropdown.__self__]
    GridLayout:
        cols: 1
        padding: 5
        spacing: 5
        size_hint_y: None
        height: 45 * len(self.children)
        LightBox:
            Label:
                markup: True
                text: "[size=15][b]General[/b][/size]"
                halign: "left"
                valign: "middle"
                color: [.85, .85, .85, 1]
                text_size: self.size

        DarkBox:
            Label:
                size_hint_x: .8
                markup: True
                text: "[size=18][b]Data set[/b][/size]\n[size=13]Select the active taxa data set to perform operations[/size]"
                halign: "left"
                valign: "middle"
                text_size: self.size
            ProcessBt:
                id: active_taxa_set
                text: "All taxa"
                on_release: dataset_dropdown.open(self)

            DropDown:
                id: dataset_dropdown
                on_select: active_taxa_set.text = args[1]
                canvas.before:
                    Color:
                        rgba: (0,0,0,1)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Widget:
                    size_hint_y: None
                    height: 3
                ProcessBt:
                    background_color: (1,1,1,.3)
                    text: 'All taxa'
                    size_hint_y: None
                    height: 40
                    on_release: dataset_dropdown.select(self.text)
                Widget:
                    size_hint_y: None
                    height: 3
                ProcessBt:
                    background_color: (1,1,1,.3)
                    text: 'Active taxa'
                    size_hint_y: None
                    height: 40
                    on_release: dataset_dropdown.select(self.text)


        Hseparator

        DarkBox:
            Label:
                size_hint_x: .8
                markup: True
                text: "[size=18][b]Output Format[/b][/size]\n[size=13]Choose the format of the output file(s). Multiple formats may be chosen[/size]"
                halign: "left"
                valign: "middle"
                text_size: self.size
            ProcessBt:
                id: conv_formatbt
                text: "Fasta"
                on_release: app.dialog_format()
        Hseparator

        DarkBox:
            id: dark_l
            Label:
                id: output_label
                size_hint_x: .8
                markup: True
                text: "[size=18][b]Output file[/b][/size]\n[size=13]Save output file to...[/size]"
                halign: "left"
                valign: "middle"
                text_size: self.size
            ProcessBt:
                id: conv
                text: "Select..."
                on_release: app.dialog_filechooser("main_output")

        BoxLayout:
            padding: [100,10,100,10]
            size_hint_y: None
            height: 60
            Button:
                bold: True
                id: opt_bt
                text: "Show additional options"
                on_release:
                    app.toggle_process_options()

#===============================================================================
# PROCESS ADDITIONAL OPTIONS
#===============================================================================

<AdditionalProcessContents@TabbedPanel>:
    do_default_tab: False
    tab_pos: "top_left"
    background_color: (0,0,0,0)
    opacity: 0

    TabbedPanelItem:
        id: main_tab
        text: "Formatting"

        GridLayout:
            id: main_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    markup: True
                    text: "[size=15][b]Formatting options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Interleave[/b][/size]\n[size=13]If sequences should be in interleave format or leave"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                Switch:
                    id: interleave
                    size_hint_x: .2
                    on_active:
                        app.update_process_switch("interleave", self.active)

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]ZORRO weights support[/b][/size]\n[size=13]Concatenation only. Concatenates auxiliary Zorro weight files into a single *_zorro.out file."
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                ProcessBt:
                    id: zorro
                    background_normal: "data/backgrounds/bt_process_off.png"
                    size_hint_x: .2
                    text: "OFF"
                    disabled: True
                    on_release:
                        app.dialog_zorro()

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Substitution model[/b][/size]\n[size=13] Specify the substitution model. Only supported for Nexus and Phylip formats"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                ProcessBt:
                    text: "Select..."
                    disabled: True

    TabbedPanelItem:
        id: partition_tab
        text: "Partitions"

        GridLayout:
            id: partition_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    markup: True
                    text: "[size=15][b]Partitioning options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    id: test2
                    text: "[size=18][b]Change/View partitions[/b][/size]\n[size=13] General options for viewing, adding or removing partitions [/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                ProcessBt:
                    id: part_dialog
                    text: "Select..."
                    disabled: True
                    on_release:
                        app.dialog_partitions()


    TabbedPanelItem:
        id: collapse_tab
        text: "Collapse"

        GridLayout:
            id: collapse_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=15][b]Sequence collapsing options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size
                Switch:
                    id: collapse
                    size_hint_x: .2
                    on_active:
                        if self.active == True: root.ids.hapbt.disabled = False; root.ids.collapse_file.disabled = False
                        if self.active == False: root.ids.hapbt.disabled = True; root.ids.collapse_file.disabled = True
                        app.update_process_switch("collapse", self.active)

            DarkBox:
                height: 70
                Label:
                    size_hint_x: .8
                    markup: True
                    id: test2
                    text: "[size=18][b]Save in new output file[/b][/size]\n[size=13] If checked, the collapsed alignments will be saved in a file with an '_haplotype' suffix in addition to the main output file[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                CheckBox:
                    id: collapse_file
                    size_hint_x: .2
                    disabled: True
                    on_active:
                        app.update_process_switch("collapse_file", self.active)

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    id: test2
                    text: "[size=18][b]Haplotype prefix[/b][/size]\n[size=13] Select the prefix name for the haplotypes [/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                ProcessBt:
                    id: hapbt
                    disabled: True
                    text: "Select..."
                    on_release:
                        app.dialog_text("Haplotype prefix")

    TabbedPanelItem:
        id: filter_tab
        text: "Filter"

        GridLayout:
            id: filter_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=15][b]Sequence filter options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size
                Switch:
                    id: filter
                    size_hint_x: .2
                    on_active:
                        if self.active == True: root.ids.cv_filterbt.disabled = False; root.ids.filter_file.disabled = False
                        if self.active == False: root.ids.cv_filterbt.disabled = True; root.ids.filter_file.disabled = True
                        app.update_process_switch("filter", self.active)

            DarkBox:
                height: 70
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Save in new output file[/b][/size]\n[size=13] If checked, the filtered alignments will be saved in a file with an '_filtered' suffix in addition to the main output file[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                CheckBox:
                    id: filter_file
                    size_hint_x: .2
                    disabled: True
                    on_active:
                        app.update_process_switch("filter_file", self.active)

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    id: test2
                    text: "[size=18][b]Gap/Missing data filter[/b][/size]\n[size=13] Set filters to remove alignment columns with excessive gap and/or missing data [/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                ProcessBt:
                    id: cv_filterbt
                    disabled: True
                    text: "Set filters"
                    on_release: app.dialog_filter()

    TabbedPanelItem:
        id: gcoder_tab
        text: "Gcoder"

        GridLayout:
            id: gcoder_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=15][b]Gap coding options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size
                Switch:
                    id: gcoder
                    size_hint_x: .2
                    disabled: True
                    on_active:
                        if self.active == True: root.ids.gcoder_file.disabled = False
                        if self.active == False: root.ids.gcoder_file.disabled = True
                        app.update_process_switch("gcoder", self.active)

            DarkBox:
                height: 70
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Save in new output file[/b][/size]\n[size=13] If checked, the coded alignments will be saved in a file with an '_coded' suffix in addition to the main output file[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                CheckBox:
                    id: gcoder_file
                    size_hint_x: .2
                    disabled: True
                    on_active:
                        app.update_process_switch("gcoder_file", self.active)

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Gap coding method[/b][/size]\n[size=13] Choose the coding method [/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                ProcessBt:
                    id: gcode_bt
                    disabled: True
                    text: "Choose..."

#===============================================================================
# ROOT SCREEN
#===============================================================================

FloatLayout:
    __safe_id: [file_dd.__self__, taxa_dd.__self__]
    BoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: (.7,.7,.7,1)
            Rectangle:
                source: "data/backgrounds/master_background.jpg"
                pos: self.pos
                size: self.size

        ActionBar:
            pos_hint: {'top':1}

            ActionView:
                id: av
                ActionPrevious:
                    id: ap
                    size_hint_x: None
                    app_icon: "data/backgrounds/app_icon.png"
                    background_normal: "data/backgrounds/menu_bt.png"
                    background_down: "data/backgrounds/menu_bt_down.png"
                    border: (0,0,0,0)
                    width: 100
                    #title: "Menu"
                    with_previous: False
                    on_release:
                        app.toggle_sidepanel()
                    canvas.before:
                        Color:
                            rgba: (0.180, 0.180, 0.180, .8)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                MainHeader:
                    id: h_ortho
                    text: "Orthology"
                    background_down: "data/backgrounds/orthology_down.png"
                    background_disabled_down: "data/backgrounds/orthology_down.png"
                    canvas.before:
                        Color:
                            rgba: [255, .200, .200, .3]
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    on_release:
                        idx = app.screen_names.index("Orthology")
                        app.go_screen(idx)
                        app.toggle_groups(self)

                MainHeader:
                    id: h_process
                    text: "Process"
                    background_down: "data/backgrounds/process_down.png"
                    background_disabled_down: "data/backgrounds/process_down.png"
                    canvas.before:
                        Color:
                            rgba: (0.200, 0.200, 255, .3)
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    on_release:
                        idx = app.screen_names.index("Process")
                        app.go_screen(idx)
                        app.toggle_groups(self)

                MainHeader:
                    id: h_stat
                    text: "Statistics"
                    background_down: "data/backgrounds/statistics_down.png"
                    background_disabled_down: "data/backgrounds/statistics_down.png"
                    canvas.before:
                        Color:
                            rgba: (0.200, 255, 0.200, .3)
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    on_release:
                        idx = app.screen_names.index("Statistics")
                        app.go_screen(idx)
                        app.toggle_groups(self)

        BoxLayout:
            id: bx1
            orientation: "horizontal"

            # This BoxLayout will two ScrollView layouts.
            # The first will be the side column with several buttons that will
            # switch the content in the second scrollview layout
            # The second will be the main panel containing the important content
            FloatLayout:
                id: panel_float
                size_hint_x: None
                opacity: 1.2
                BoxLayout:
                    orientation: "horizontal"
                    id: main_box
                    size_hint_x: None
                    width: 0
                    canvas.before:
                        Color:
                            rgb: (.2, .2, .2)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    # Both these ScrollView layouts are here because it is the only way
                    # that the children layouts' width will be truly 0. If a
                    # BoxLayout, Floatlayout, etc would be used, the contents would
                    # still appear.
                    ScrollView:
                        id: sp_bts
                        size_hint_x: None
                        width: 0
                        BoxLayout:
                            id: side_bt
                            orientation: "vertical"
                            SideButton:
                                size_hint: (None, None)
                                height: 60
                                width: 60
                                text: " "
                                background_down: "data/backgrounds/side_bt_home_down.png"
                                background_normal: "data/backgrounds/side_bt_home.png"
                                background_disabled_down: "data/backgrounds/side_bt_home_down.png"
                                att: "Open/View Data"
                                state: "down"
                                disabled: True
                                on_release:
                                    carousel.load_slide(carousel.slides[0])
                                    app.toggle_groups(self)
                            SideButton:
                                size_hint: (None, None)
                                height: 60
                                width: 60
                                text: " "
                                background_down: "data/backgrounds/side_bt_group_down.png"
                                background_normal: "data/backgrounds/side_bt_group.png"
                                background_disabled_down: "data/backgrounds/side_bt_group_down.png"
                                att: "Taxa Groups"
                                on_release:
                                    carousel.load_slide(carousel.slides[1])
                                    app.toggle_groups(self)
                            SideButton:
                                size_hint: (None, None)
                                height: 60
                                width: 60
                                text: " "
                                background_down: "data/backgrounds/side_bt_queue_down.png"
                                background_normal: "data/backgrounds/side_bt_queue.png"
                                background_disabled_down: "data/backgrounds/side_bt_queue_down.png"
                                id: queue
                                att: "Operations Queue"
                                on_release:
                                    app.save_operation_queue()
                                    carousel.load_slide(carousel.slides[2])
                                    app.toggle_groups(self)
                            Widget:
                                size_hint_y: .8
                                canvas.before:
                                    Color:
                                        rgba: (0.180, 0.180, 0.180, .8)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                    ScrollView:
                        id: sv_over
                        size_hint_x: None
                        width: 0
                        BoxLayout:
                            orientation: "vertical"
                            Button:
                                id: first_lb
                                background_normal: "data/backgrounds/side_panel_bt_normal.png"
                                size_hint_y: .1
                                border: (16,16,32,16)
                                text: "Some stuff"
                            Button:
                                id: second_lb
                                background_normal: "data/backgrounds/side_panel_bt_normal.png"
                                size_hint_y: .1
                                text: "Some stuff"
                            Widget:
                                size_hint_y: .8
                                canvas.before:
                                    Color:
                                        rgba: (0.180, 0.180, 0.180, .8)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                    ScrollView:
                        id: sp
                        size_hint_x: .8
                        width: 0

                        Carousel:
                            id: carousel
                            direction: "bottom"
                            BoxLayout:
                                orientation: "vertical"
                                padding: 10
                                spacing: 10
                                id: main_slide

                                canvas.before:
                                    Color:
                                        rgba: (0.180, 0.180, 0.180, .8)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                                BoxLayout:
                                    size_hint_y: None
                                    height: 50
                                    padding: (15,0,15, 0)
                                    Button:
                                        id: sv_but
                                        background_normal: "data/backgrounds/process_exec.png"
                                        background_down: "data/backgrounds/process_exec_down.png"
                                        text: "Open file(s)"
                                        bold: True
                                        border: 0,0,0,0
                                        font_size: 18

                                        on_release:
                                            idx = app.screen_names.index("fc")
                                            app.go_screen(idx)
                                            app.toggle_sidepanel()

                                TabbedPanel:
                                    id: main_tp
                                    do_default_tab: False
                                    background_color: (0,0,0,0)
                                    tab_pos: "top_mid"

                                    TabbedPanelItem:
                                        id: file_tp
                                        text: "Files"

                                        BoxLayout:
                                            orientation: "vertical"
                                            spacing: 20
                                            ScrollView:
                                                size_hint_y: .9
                                                height: root.height*.65
                                                id: sv_file
                                                GridLayout:
                                                    cols: 3
                                                    size_hint_y: None
                                                    id: file_sl
                                                    padding: 10
                                                    spacing: 5
                                                    height: 30
                                                    #minimum_height: root.height*.1

                                                    Button:
                                                        id: file_temp
                                                        height: 40
                                                        disabled: True
                                                        size_hint_y: None
                                                        #size_hint_x: None
                                                        text: "No files loaded"
                                            Label:
                                                id: file_lab
                                                size_hint_y: None
                                                height: 1
                                                color: (.6, .6, .6, 1)
                                            BoxLayout:
                                                spacing: 5
                                                size_hint_y: None
                                                height: 35
                                                BoxLayout:
                                                    id: sb_file
                                                    spacing: 5
                                                    Button:
                                                        text: "Select All"
                                                        disabled: True
                                                    Button:
                                                        text: "Deselect All"
                                                        disabled: True
                                                Button:
                                                    id: file_opt
                                                    text: "+"
                                                    font_size: 30
                                                    bold: True
                                                    size_hint_x: .15
                                                    disabled: True
                                                    on_release:
                                                        file_dd.open(self)
                                                DropDown:
                                                    id: file_dd
                                                    auto_width: False
                                                    size_hint_x: None
                                                    width: 250
                                                    Button:
                                                        text_size: self.size
                                                        halign: "left"
                                                        valign: "middle"
                                                        size_hint: (None, None)
                                                        width: 250
                                                        height: 30
                                                        text: "  Export all file names as text"
                                                        on_release:
                                                            app.dialog_filechooser("export")
                                                            app.export_mode = ("file", "all")
                                                            file_dd.dismiss()
                                                    Button:
                                                        text_size: self.size
                                                        halign: "left"
                                                        valign: "middle"
                                                        size_hint: (None, None)
                                                        width: 250
                                                        height: 30
                                                        text: "  Export selected file names as text"
                                                        on_release:
                                                            app.dialog_filechooser("export")
                                                            app.export_mode = ("file", "selected")
                                                            file_dd.dismiss()
                                    TabbedPanelItem:
                                        id: taxa_tp
                                        text: "Taxa"
                                        BoxLayout:
                                            orientation: "vertical"
                                            spacing: 20
                                            ScrollView:
                                                size_hint_y: .9
                                                height: root.height*.65
                                                id: sv_sp
                                                GridLayout:
                                                    cols: 3
                                                    size_hint_y: None
                                                    id: taxa_sl
                                                    padding: 10
                                                    spacing: 5
                                                    Button:
                                                        id: species_temp
                                                        height: 40
                                                        disabled: True
                                                        size_hint_y: None
                                                        text: "No species loaded"
                                            Label:
                                                id: sp_lab
                                                size_hint_y: None
                                                height: 1
                                                color: (.6, .6, .6, 1)
                                            BoxLayout:
                                                spacing: 5
                                                size_hint_y: None
                                                height: 35
                                                BoxLayout:
                                                    id: sb_taxa
                                                    spacing: 5
                                                    Button:
                                                        text: "Select All"
                                                        disabled: True
                                                    Button:
                                                        text: "Deselect All"
                                                        disabled: True
                                                Button:
                                                    id: taxa_opt
                                                    text: "+"
                                                    font_size: 30
                                                    bold: True
                                                    size_hint_x: .15
                                                    disabled: True
                                                    on_release:
                                                        taxa_dd.open(self)

                                                DropDown:
                                                    id: taxa_dd
                                                    auto_width: False
                                                    size_hint_x: None
                                                    width: 250
                                                    Button:
                                                        text_size: self.size
                                                        halign: "left"
                                                        valign: "middle"
                                                        size_hint: (None, None)
                                                        width: 250
                                                        height: 30
                                                        text: " Export all taxa names as text"
                                                        on_release:
                                                            app.dialog_filechooser("export")
                                                            app.export_mode = ("taxa", "all")
                                                            taxa_dd.dismiss()
                                                    Button:
                                                        text_size: self.size
                                                        halign: "left"
                                                        valign: "middle"
                                                        size_hint: (None, None)
                                                        width: 250
                                                        height: 30
                                                        text: " Export selected taxa names as text"
                                                        on_release:
                                                            app.dialog_filechooser("export")
                                                            app.export_mode = ("taxa", "selected")
                                                            taxa_dd.dismiss()
                            BoxLayout:
                                orientation: "vertical"
                                padding: 10
                                spacing: 5
                                canvas.before:
                                    Color:
                                        rgba: (0.180, 0.180, 0.180, .8)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                                Label:
                                    size_hint_y: .1
                                    text: "Taxa groups"
                                    font_size: 18
                                    halign: "center"
                                    valign: "middle"
                                    text_size: self.size
                                    bold: True
                                    canvas.before:
                                        Color:
                                            rgba: .35, .35, .35, 1
                                        Rectangle:
                                            pos: self.pos
                                            size: self.size
                                Hseparator
                                ScrollView:
                                    size_hint_y: .8
                                    GridLayout:
                                        id: group_grid
                                        size_hint_y: None
                                        height: 0
                                        padding: 5
                                        spacing: 5
                                        cols: 2
                                Button:
                                    size_hint_y: .1
                                    bold: True
                                    text: "Set new taxa group"
                                    id: tx_group_bt
                                    disabled: True
                                    on_release:
                                        app.dialog_taxagroup()

                            BoxLayout:
                                orientation: "vertical"
                                padding: 10
                                spacing: 5
                                canvas.before:
                                    Color:
                                        rgba: (0.180, 0.180, 0.180, .8)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                                Label:
                                    size_hint_y: .1
                                    text: "Operations queue"
                                    font_size: 18
                                    halign: "center"
                                    valign: "middle"
                                    text_size: self.size
                                    bold: True
                                    canvas.before:
                                        Color:
                                            rgba: .35, .35, .35, 1
                                        Rectangle:
                                            pos: self.pos
                                            size: self.size
                                Hseparator
                                ScrollView:
                                    size_hint_y: .8
                                    id: op_sv
                                Widget:
                                    size_hint_y: .1


            ScreenManager:
                id: sm

