#:kivy 1.8.0

<ShowcaseScreen>:
    ScrollView:
        do_scroll_x: False
        do_scroll_y: False if root.fullscreen else (content.height > root.height - dp(16))
        AnchorLayout:
            size_hint_y: None
            height: root.height if root.fullscreen else max(root.height, content.height)
            GridLayout:
                id: content
                cols: 1

<SaveDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        spacing:10

        FileChooserListView:
            id: sd_filechooser
            text: "master"
            on_selection: text_input.text = self.selection

        BoxLayout:
            orientation: "horizontal"
            size_hint_y: None
            height: 30
            Label:
                size_hint_x: None
                width: 100
                text: "File name:"
            TextInput:
                id: text_input
                multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30

            Button:
                text: "Save"
                on_release: app.save_file(sd_filechooser.path, text_input.text, sd_filechooser.text)

            Button:
                text: "Cancel"
                on_release: root.cancel()

<FormatDialog>:
    padding: 30
    spacing: 10
    orientation: "vertical"
    id: format_dlg
    ToggleButton:
        id: fasta
        state: "down"
        text: "Fasta"
    ToggleButton:
        id: phylip
        text: "Phylip"
    ToggleButton:
        id: nexus
        text: "Nexus"
    ToggleButton:
        id: mcmctree
        text: "MCMCTree"
    ToggleButton:
        id: ima2
        text: "IMa2"
        disabled: True

    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Done"
            on_release: app.save_format(format_dlg)
        Button:
            text: "Cancel"
            on_release: root.cancel()

<TextDialog>:
    TextInput
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Done"
            on_release: app.save_format(format_dlg)
        Button:
            text: "Cancel"
            on_release: root.cancel()

<FilterDialog>:
    orientation: "vertical"
    padding: 20
    spacing: 20

    Label:
        text: "Gap threshold"
        bold: True
        halign: "left"
        valign: "middle"
        text_size: self.size

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: 30
        spacing: 20
        Slider:
            id: gap_sli
            size_hint_x: .85
            min: 0
            max: 100
            step: 1
            value: 25
        TextInput:
            size_hint_x: .15
            id: gap_ti
            text: "{}".format(round(gap_sli.value))
            multiline: False
            on_text_validate: if app.filter_validater(gap_ti.text): gap_sli.value = app.filter_validater(gap_ti.text)[1]

    Label:
        text: "Missing data threshold"
        bold: True
        halign: "left"
        valign: "middle"
        text_size: self.size

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: 30
        spacing: 20
        Slider:
            id: mis_sli
            size_hint_x: .85
            min: 0
            max: 100
            step: 1
            value: 50
        TextInput:
            size_hint_x: .15
            id: mis_ti
            text: "{}".format(round(mis_sli.value))
            multiline: False
            on_text_validate: if app.filter_validater(mis_ti.text): mis_sli.value = app.filter_validater(mis_ti.text)[1]

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: 30
        Button:
            text: "Done"
            on_release: app.save_filter(gap_sli.value, mis_sli.value)
        Button:
            text: "Cancel"
            on_release: root.cancel()

<MainHeader@ActionToggleButton>:
    size_hint_x: 1
    font_size: 20
    bold: True
    group: "main_header"
    disabled_color: (1, 1, 1, 1)

<SelectionBox@BoxLayout>:
    orientation: "horizontal"
    size_hint_y: .11
    spacing: 20
    Button:
        text: "Select All"
        disabled: True
    Button:
        text: "Deselect All"
        disabled: True

<SideButton@ToggleButton>:
    group: "side_buttons"
    size_hint_y: .1
    font_size: 30
    bold: True
    background_down: "data/backgrounds/side_panel_bt_down.png"
    background_normal: "data/backgrounds/side_panel_bt_normal.png"
    background_disabled_down: "data/backgrounds/side_panel_bt_down.png"
    disabled_color: (1,1,1,1)

############################ PROCESS SCREEN ####################################

<Sidebt@ToggleButton>:
    #background_color: [0,0,0,1]
    size_hint_y: None
    height: 70
    background_normal: "data/backgrounds/bt_sideprocess_normal.png"
    background_down: "data/backgrounds/bt_sideprocess.png"
    background_disabled_down: "data/backgrounds/bt_sideprocess.png"
    disabled_color: (1, 1, 1, 1)
    halign: "left"
    valign: "middle"
    text_size: self.size
    bold: True
    font_size: 16
    padding: (20, 0)

# Vertical light grey separator
<Vseparator@Widget>:
    size_hint_x: None
    width: 3
    canvas:
        Color:
            rgb: .5, .5, .5
        Rectangle:
            pos: self.center_x, -5
            size: .3, self.height

<LightBox@BoxLayout>:
    height: 40
    orientation: "horizontal"
    size_hint_y: None
    padding: 10
    canvas.before:
        Color:
            rgba: (.2, .2, .2, .8)
        Rectangle:
            pos: self.pos
            size: self.size

<DarkBox@BoxLayout>:
    height: 60
    orientation: "horizontal"
    size_hint_y: None
    padding: 10

<Hseparator@Widget>:
    size_hint_y: None
    height: self.thickness + 2 * self.margin
    thickness: 1
    margin: 1
    canvas:
        Color:
            rgb: .5, .5, .5
        Rectangle:
            pos: self.x + self.margin, self.y + self.margin +1
            size: self.width - 2 * self.margin, self.thickness

BoxLayout:
    orientation: "vertical"

    ActionBar:
        pos_hint: {'top':1}

        ActionView:
            id: av
            ActionPrevious:
                id: ap
                size_hint_x: 0.2
                with_previous: False
                on_release:
                    app.side_panel_toggle()
                canvas.before:
                    Color:
                        rgba: (0.180, 0.180, 0.180, .8)
                    Rectangle:
                        pos: self.pos
                        size: self.size

            MainHeader:
                id: h_ortho
                text: "Orthology"
                background_down: "data/backgrounds/orthology_down.png"
                background_disabled_down: "data/backgrounds/orthology_down.png"
                canvas.before:
                    Color:
                        rgba: [255, .200, .200, .8]
                    Rectangle:
                        pos: self.pos
                        size: self.size
                on_release:
                    idx = app.screen_names.index("Orthology")
                    app.go_screen(idx)
                    app.toggle_groups(self)

            MainHeader:
                id: h_process
                text: "Process"
                background_down: "data/backgrounds/process_down.png"
                background_disabled_down: "data/backgrounds/process_down.png"
                canvas.before:
                    Color:
                        rgba: (0.200, 0.200, 255, .8)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                on_release:
                    idx = app.screen_names.index("Process")
                    app.go_screen(idx)
                    app.toggle_groups(self)

            MainHeader:
                id: h_stat
                text: "Statistics"
                background_down: "data/backgrounds/statistics_down.png"
                background_disabled_down: "data/backgrounds/statistics_down.png"
                canvas.before:
                    Color:
                        rgba: (0.200, 255, 0.200, .8)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                on_release:
                    idx = app.screen_names.index("Statistics")
                    app.go_screen(idx)
                    app.toggle_groups(self)

            ActionButton:
                size_hint_x: 0.2

    BoxLayout:
        id: bx1
        orientation: "horizontal"

        # This BoxLayout will two ScrollView layouts.
        # The first will be the side column with several buttons that will
        # switch the content in the second scrollview layout
        # The second will be the main panel containing the important content
        FloatLayout:
            id: panel_float
            size_hint_x: None
            opacity: 1.2
            BoxLayout:
                orientation: "horizontal"
                id: main_box
                size_hint_x: None
                width: 0
                canvas.before:
                    Color:
                        rgb: (.2, .2, .2)
                    Rectangle:
                        pos: self.pos
                        size: self.size

                # Both these ScrollView layouts are here because it is the only way
                # that the children layouts' width will be truly 0. If a
                # BoxLayout, Floatlayout, etc would be used, the contents would
                # still appear.
                ScrollView:
                    id: sp_bts
                    size_hint_x: None
                    width: 0
                    BoxLayout:
                        orientation: "vertical"
                        SideButton:
                            id: first_sidebt
                            state: "down"
                            disabled: True
                            text: "H"
                            on_release:
                                carousel.load_slide(carousel.slides[0])
                                app.toggle_groups(self)
                        SideButton:
                            id: second_sidebt
                            text: "G"
                            on_release:
                                carousel.load_slide(carousel.slides[1])
                                app.toggle_groups(self)
                        Widget:
                            size_hint_y: .8
                            canvas.before:
                                Color:
                                    rgba: (0.180, 0.180, 0.180, .8)
                                Rectangle:
                                    pos: self.pos
                                    size: self.size
                ScrollView:
                    id: sv_over
                    size_hint_x: None
                    width: 0
                    BoxLayout:
                        orientation: "vertical"
                        Button:
                            id: first_lb
                            background_normal: "data/backgrounds/side_panel_bt_normal.png"
                            size_hint_y: .1
                            border: (16,16,32,16)
                            text: "Some stuff"
                        Button:
                            id: second_lb
                            background_normal: "data/backgrounds/side_panel_bt_normal.png"
                            size_hint_y: .1
                            text: "Some stuff"
                        Widget:
                            size_hint_y: .8
                            canvas.before:
                                Color:
                                    rgba: (0.180, 0.180, 0.180, .8)
                                Rectangle:
                                    pos: self.pos
                                    size: self.size

                ScrollView:
                    id: sp
                    size_hint_x: .8
                    width: 0

                    Carousel:
                        id: carousel
                        direction: "bottom"
                        BoxLayout:
                            orientation: "vertical"
                            padding: 10
                            spacing: 10
                            id: main_slide

                            canvas.before:
                                Color:
                                    rgba: (0.180, 0.180, 0.180, .8)
                                Rectangle:
                                    pos: self.pos
                                    size: self.size

                            Button:
                                id: sv_but
                                text: "Open file(s)"
                                size_hint_y: None
                                height: 50
                                on_release:
                                    idx = app.screen_names.index("fc")
                                    app.go_screen(idx)
                                    app.side_panel_toggle()

                            TabbedPanel:
                                id: main_tp
                                do_default_tab: False
                                background_color: (0,0,0,0)
                                tab_pos: "top_mid"

                                TabbedPanelItem:
                                    id: file_tp
                                    text: "Files"

                                    BoxLayout:
                                        orientation: "vertical"
                                        spacing: 20
                                        ScrollView:
                                            size_hint_y: .9
                                            height: root.height*.65
                                            id: sv_file
                                            GridLayout:
                                                cols: 3
                                                size_hint_y: None
                                                id: file_sl
                                                padding: 10
                                                spacing: [5, 10]
                                                height: root.height*.2
                                                minimum_height: root.height*.1

                                                Button:
                                                    id: file_temp
                                                    height: root.height*.08
                                                    disabled: True
                                                    size_hint_y: None
                                                    #size_hint_x: None
                                                    text: "No files loaded"
                                        Label:
                                            id: file_lab
                                            size_hint_y: None
                                            height: 1
                                            color: (.6, .6, .6, 1)
                                        SelectionBox:
                                            id: sb_file

                                TabbedPanelItem:
                                    id: taxa_tp
                                    text: "Taxa"
                                    BoxLayout:
                                        orientation: "vertical"
                                        spacing: 20
                                        ScrollView:
                                            size_hint_y: .9
                                            height: root.height*.65
                                            id: sv_sp
                                            GridLayout:
                                                cols: 3
                                                size_hint_y: None
                                                id: taxa_sl
                                                padding: 10
                                                spacing: [5, 10]
                                                Button:
                                                    id: species_temp
                                                    height: root.height*.08
                                                    disabled: True
                                                    size_hint_y: None
                                                    text: "No species loaded"
                                        Label:
                                            id: sp_lab
                                            size_hint_y: None
                                            height: 1
                                            color: (.6, .6, .6, 1)
                                        SelectionBox:
                                            id: sb_taxa
                        BoxLayout:
                            Button

        ScreenManager:
            id: sm

