#:kivy 1.9.0
#:import Factory kivy.factory.Factory
#:import sep os.sep
#:import multiprocessing multiprocessing
#:import ObjectProperty kivy.properties.ObjectProperty
#:import StringProperty kivy.properties.StringProperty
#:import ListProperty kivy.properties.ListProperty


<ShowcaseScreen>:
    ScrollView:
        do_scroll_x: False
        do_scroll_y: False if root.fullscreen else (content.height > root.height - dp(16))
        AnchorLayout:
            size_hint_y: None
            height: root.height if root.fullscreen else max(root.height, content.height)
            GridLayout:
                id: content
                cols: 1

#===============================================================================
# GENERAL USAGE
#===============================================================================

<TFSpinnerOpt@SpinnerOption>:
    bold: True
    background_normal: "data/backgrounds/spinner_opt.png"

<TFButton@Button>:
    bold: True
    halign: "center"
    valign: "middle"
    text_size: self.size
    size_hint_y: None
    height: 30
    background_normal: "data/backgrounds/bt_process.png"
    background_down: "data/backgrounds/bt_process_off.png"

<TGToggleButton@ToggleButton>:
    bold: True
    state: "down"
    halign: "center"
    valign: "middle"
    text_size: self.size
    size_hint_y: None
    height: 30
    background_normal: "data/backgrounds/bt_process_off.png"
    background_down: "data/backgrounds/bt_process.png"

<CrunchData@BoxLayout>:
    orientation: "vertical"
    AnchorLayout:
        anchor_x: "center"
        anchor_y: "top"
        size_hint_y: .6
        Image:
            size_hint: None, None
            id: img
            source: "data/backgrounds/image-loading.gif"
    Label:
        size_hint_y: .4
        text: "Crunching data..."
        bold: True
        halign: "center"
        valign: "top"
        text_size: self.size
        color: (0.216, 0.67, 0.784, 1)

#===============================================================================
# ROOT WINDOW
#===============================================================================

<WarningFloat@Label>:
    root_pos: [0, 0]
    size_hint: None, None
    padding: (10, 15)
    halign: "left"
    valign: "middle"
    width: len(self.text) * 9 if len(self.text) * 9 < 400 else 400
    text_size: (self.size[0], None)
    height: self.texture_size[1]
    pos: self.root_pos[0] - self.size[0] - 20, self.root_pos[1] - self.size[1] - 60
    cl: (.7, .33, .33, 1)
    line_cl: (1, 0.3, 0.3, 1)
    bold: True
    canvas.before:
        Color:
            rgba: self.cl
        Rectangle:
            pos: self.pos
            size: self.size
    StackLayout:
        canvas.after:
            Color:
                rgb: root.line_cl
            Line:
                width: 1.1
                cap: "round"
                joint: "round"
                rectangle: root.x,root.y,root.width,root.height

<RemoveFloat@Button>:
    size_hint: None, None
    background_normal: "data/backgrounds/round_remove.png"
    background_down: "data/backgrounds/round_remove.png"
    size: 25, 25

#===============================================================================
# FILECHOOSER
#===============================================================================

<PathLabel@Label>:
    size_hint_x: .93
    text_size: (self.size[0] - 20, self.size[1])
    shorten: True
    text: app.home_path
    shorten_from: "left"
    halign: "left"
    valign: "middle"
    canvas.before:
        Color:
            rgba: .35, .35, .35, 1
        Rectangle:
            pos: self.pos
            size: self.size

<PathText>:
    size_hint_x: .93
    multiline: False
    text: app.home_path

<FileTypeBt@ToggleButton>:
    bold: True
    background_normal: "data/backgrounds/main_op_bt.png"
    background_down: "data/backgrounds/bt_sideprocess.png"
    background_disabled_down: "data/backgrounds/bt_sideprocess.png"
    disabled_color: (1,1,1,1)
    group: "file_type"
    on_release:
        app.toggle_groups(self)

<LoadProgressDialog@BoxLayout>:
    padding: 10
    orientation: "vertical"
    proc_kill: False

    Label:
        id: msg
        bold: True
        halign: "center"
        valign: "middle"
        text_size: self.size
        #shorten: True

    ProgressBar:
        max: 10
        id: pb

    BoxLayout:
        size_hint_y: None
        height: 30
        padding: (30, 0, 30, 0)
        Button:
            id: close_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Cancel"
            bold: True
            on_release:
                root.proc_kill = True


#===============================================================================
# MOUSE OVER
#===============================================================================

<FancyButton@Button>:
    size_hint: None, None
    background_disabled_normal: "data/backgrounds/fancy_mo_background.png"
    disabled: True
    disabled_color: (1,1,1,1)
    bold: True
    line_clr: (1,1,1,1)
    StackLayout:
        canvas.after:
            Color:
                rgb: root.line_clr
            Line:
                width: 0.8
                cap: "round"
                joint: "round"
                rectangle: root.x,root.y,root.width,root.height

<FancyMarker@Button>:
    size_hint: None, None
    border: 0,0,0,0

<MouseOverLabel@Button>:
    text_size: self.size
    halign: "center"
    valign: "middle"
    background_down: "atlas://data/images/defaulttheme/button"

<SideLabel>:
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            source: "data/backgrounds/side_label.png"
            pos: self.pos
            size: self.size

#===============================================================================
# PLOT SCREEN
#===============================================================================

<MySlider@Slider>:
    FancyMarker:
        pos: (root.value_pos[0] - 6, root.center_y + 15)
        background_normal: "data/backgrounds/box_arrow_down.png"
        size: 12, 7
        background_color: (0.216, 0.67, 0.784, 1)
        opacity: 1 if root.collide_point(app.mouse_position[0], app.mouse_position[1]) else 0
    FancyButton:
        text: str(root.value).split(".")[0]
        size: 30, 20
        pos: (root.value_pos[0] - 15, root.center_y + 22.5)
        background_color: (0.216, 0.67, 0.784, 1)
        line_clr: (0.216, 0.67, 0.784, 1)
        opacity: 1 if root.collide_point(app.mouse_position[0], app.mouse_position[1]) else 0

<BackButton@Button>:
    size_hint: None, None
    size: 80,30
    text: "  Back"
    bold: True
    opacity: .2
    background_normal: "data/backgrounds/go_back_bt.png"
    on_release:
        app.go_previous_screen()

<PlotToolbar@BoxLayout>:
    orientation: "vertical"
    size_hint: None, None
    size: 50, 240
    opacity: .2
    canvas.before:
        Color:
            rgba: (.2,.2,.2,1)
        Rectangle:
            pos: self.pos
            size: self.size

    AnchorLayout:
        anchor_x: "center"
        anchor_y: "center"
        BoxLayout:
            orientation: "vertical"
            size_hint: None, None
            size: 40, 220
            spacing: 5
            id: content
            Button
                size_hint: None, None
                size: 40, 40
                background_normal: "data/backgrounds/zoom_in.png"
                on_release:
                    app.screen.ids.plot_content.scale += .1
            Button
                size_hint: None, None
                size: 40, 40
                background_normal: "data/backgrounds/zoom_out.png"
                on_release:
                    app.screen.ids.plot_content.scale -= .1 if app.screen.ids.plot_content.scale > 0.5 else 0
            Button:
                size_hint: None, None
                size: 40, 40
                background_normal: "data/backgrounds/fit_plot.png"
                on_release:
                    app.screen.ids.plot_content.scale = 1
                    app.screen.ids.plot_content.pos = (0, 0)
            Button:
                size_hint: None, None
                size: 40, 40
                id: export_fig
                background_normal: "data/backgrounds/export_fig.png"
                on_release:
                    app.dialog_export_graphic()
            Button:
                size_hint: None, None
                size: 40, 40
                id: export_table
                background_normal: "data/backgrounds/export_table.png"
                on_release:
                    app.dialog_filechooser("export_table")

<ExportGroupDialog@BoxLayout>:
    orientation: "vertical"
    padding: 10
    spacing: 10
    BoxLayout:
        orientation: "vertical"
        size_hint_y: None
        height: 40
        BoxLayout:
            spacing: 10
            FileTypeBt:
                state: "down"
                disabled: True
                id: group_fmt
                text: "Groups file"
            FileTypeBt:
                id: prot_fmt
                text: "Protein sequences"
            FileTypeBt:
                id: nuc_fmt
                text: "Nucleotide sequences"

    Hseparator:
        thickness: 1.5

    DarkBox:
        height: 70
        Label:
            opacity: .2 if group_fmt.state == "down" else 1
            size_hint_x: .7
            markup: True
            text: "[size=18][b]Protein database[/b][/size]\n[size=13]Provide a Fasta or .dic file containing the proteins used as a database for the Search operation. [/size]"
            halign: "left"
            valign: "middle"
            text_size: self.size
        ProcessBt:
            disabled: True if group_fmt.state == "down" else False
            text: app.protein_db if app.protein_db else "Select..."
            on_release:
                app.dialog_filechooser("protein_db")

    Hseparator:
        thickness: .5

    DarkBox:
        height: 70
        Label:
            opacity: .2 if group_fmt.state == "down" or prot_fmt.state == "down" else 1
            size_hint_x: .7
            markup: True
            text: "[size=18][b]CDS database[/b][/size]\n[size=13]Provide a Fasta file containing the nucleotide CDS files that correspond to the searched proteins[/size]"
            halign: "left"
            valign: "middle"
            text_size: self.size
        ProcessBt:
            disabled: True if group_fmt.state == "down" or prot_fmt.state == "down" else False
            text: "Select"

    Hseparator:
        thickness: 1.5

    BoxLayout:
        size_hint_y: None
        height: 30
        AnchorLayout:
            anchor_x: "center"
            anchor_y: "center"
            BoxLayout:
                size_hint_x: None
                width: 220
                spacing: 20
                Button:
                    background_normal: "data/backgrounds/bt_process.png"
                    background_down: "data/backgrounds/bt_process_off.png"
                    text: "Export"
                    id: ok_bt
                    size_hint_x: None
                    width: 100
                    bold: True
                    on_release:
                        if prot_fmt.state == "down" and not app.protein_db: \
                        app.dialog_floatcheck("Please provide a protein database", t="error")
                        elif nuc_fmt.state == "down" and not app.protein_db and not app.cds_db: \
                        app.dialog_floatcheck("Please provide a protein and/or CDS database(s)", t="error")
                        elif prot_fmt.state == "down": \
                        app.dialog_export_groups_filechooser("protein")
                        elif group_fmt.state == "down": \
                        app.dialog_export_groups_filechooser("group")
                        elif nuc_fmt.state == "down": \
                        app.dialog_export_groups_filechooser("nucleotide")

                Button:
                    background_normal: "data/backgrounds/bt_process_off.png"
                    background_down: "data/backgrounds/bt_process.png"
                    id: cancel_bt
                    bold: True
                    text: "Cancel"
                    size_hint_x: None
                    width: 100
                    on_release: root.cancel()

<ExportGraphics@BoxLayout>:
    size: root.size
    pos: root.pos
    orientation: "vertical"
    spacing: 10
    padding: 10

    BoxLayout:
        size_hint_y: None
        height: 30
        spacing: 10
        Label:
            padding: (5, 0)
            canvas.before:
                Color:
                    rgba: .35, .35, .35, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            text: sd_filechooser.path
            halign: "left"
            valign: "middle"
            text_size: self.size
        Button:
            bold: True
            size_hint_x: None
            width: 100
            text: "New folder"
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            on_release:
                app.dialog_text("New folder", "new_folder")

    FileChooserL:
        id: sd_filechooser
        text: "master"
        path: app._common_path() if app._common_path() else app.home_path
        on_selection: text_input.text = self.selection

    BoxLayout:
        size_hint_y: None
        height: 30
        spacing: 5
        Label:
            size_hint_x: None
            width: 80
            text: "File name:"
        TextInput:
            id: text_input
            multiline: False
        Spinner:
            size_hint_x: None
            width: 80
            id: ext
            text: ".png"
            values: [".png", ".svg", ".pdf"]

    AnchorLayout:
        size_hint_y: None
        height: 30
        anchor_x: "center"
        anchor_y: "center"
        BoxLayout:
            size_hint_x: None
            width: 140
            spacing: 20
            Button:
                background_normal: "data/backgrounds/bt_process.png"
                background_down: "data/backgrounds/bt_process_off.png"
                text: "Save"
                id: ok_bt
                size_hint_x: None
                width: 100
                bold: True
                on_release:
                    if text_input.text == "": \
                    app.dialog_floatcheck("Please specify a file name", t="error")
                    else: \
                    app.export_graphic(sd_filechooser.path, text_input.text, ext.text)
                    root.cancel()
            Button:
                background_normal: "data/backgrounds/bt_process_off.png"
                background_down: "data/backgrounds/bt_process.png"
                id: cancel_bt
                bold: True
                text: "Cancel"
                size_hint_x: None
                width: 100
                on_release: root.cancel()

#===============================================================================
# GENERAL INFORMATIVE POPUP
#===============================================================================

<InfoPopup@BoxLayout>:
    orientation: "vertical"
    padding: 10
    spacing: 10
    ScrollView:
        GridLayout:
            cols: 1
            padding: 10
            size_hint_y: None
            height: content.texture_size[1] * 1.1

            Label:
                id: content
                size_hint: (1, None)
                text_size: self.width, None
                size: self.parent.width, self.texture_size[1]
                markup: True
                font_size: 15
                line_height: 1
                halign: "justify"

    BoxLayout:
        size_hint_y: None
        height: 30
        padding: (100, 0, 100, 0)
        Button:
            id: close_bt
            text: "Close"
            bold: True
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            on_release:
                root.cancel()

<InfoBt@Button>:
    size_hint: (None, None)
    border: 0,0,0,0
    background_normal: "data/backgrounds/more_info.png"
    background_down: "data/backgrounds/more_info_down.png"

#===============================================================================
# TAXA/FILE INFORMATIVE POPUPS
#===============================================================================

<PopupLabel@Label>:
    bold: True
    halign: "left"
    valign: "middle"
    text_size: self.size
    size_hint_x: .6

<PopupText@TextInput>:
    multiline: False
    readonly: True
    size_hint_x: .4

<PopupBox@BoxLayout>:
    size_hint_y: None
    height: 30
    spacing: 10

<ProteomePopup@BoxLayout>
    orientation: "vertical"
    padding: 10
    spacing: 5
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        PopupBox:
            PopupLabel:
                text: "Number of sequences:"
            PopupText:
                id: n_seq
        PopupBox:
            PopupLabel:
                text: "Sequence size:"
            PopupText:
                id: n_res

        Widget
    BoxLayout:
        size_hint_y: None
        height: 30
        padding: (100, 0, 100, 0)
        Button:
            id: close_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            bold: True
            text: "Close"
            on_release:
                root.cancel()

<FilePopup@BoxLayout>
    orientation: "vertical"
    padding: 10
    spacing: 5
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        PopupBox:
            PopupLabel:
                text: "Input format:"
            PopupText:
                id: in_format
        PopupBox:
            PopupLabel:
                text: "Sequence type:"
            PopupText:
                id: seq_type
        PopupBox:
            PopupLabel:
                text: "Alignment:"
            PopupText:
                id: is_aln
        PopupBox:
            PopupLabel:
                text: "Sequence size:"
            PopupText:
                id: seq_size
        PopupBox:
            PopupLabel:
                text: "Number of taxa:"
            PopupText:
                id: n_taxa
        Widget
    BoxLayout:
        size_hint_y: None
        height: 30
        padding: (100, 0, 100, 0)
        Button:
            id: close_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            bold: True
            text: "Close"
            on_release:
                root.cancel()

<TaxaPopup>
    orientation: "vertical"
    size_hint_y: None
    padding: 15
    spacing: 5
    PopupLabel:
        background_color: (.7, .7, .7)
        id: dataset_label
        halign: "center"
        size_hint_x: 1
        size_hint_y: None
        height: 30
        canvas.before:
            Color:
                rgba: .35, .35, .35, 1
            Rectangle:
                pos: self.pos
                size: self.size
    PopupBox:
        PopupLabel:
            #size_hint_x: .45
            text: "Sequence length:"
        PopupText:
            #size_hint_x: .55
            id: seq_len
    PopupBox:
        PopupLabel:
            #size_hint_x: .45
            text: "Number of indels:"
        PopupText:
            #size_hint_x: .55
            id: indels
    PopupBox:
        PopupLabel:
            #size_hint_x: .65
            text: "Number of missing data:"
        PopupText:
            #size_hint_x: .35
            id: missing
    PopupBox:
        PopupLabel:
            #size_hint_x: .7
            text: "Effective sequence length:"
        PopupText:
            #size_hint_x: .3
            id: ef_seq_len
    PopupBox:
        PopupLabel:
            #size_hint_x: .35
            text: "File coverage"
        PopupText:
            #size_hint_x: .65
            id: file_cov

<CloseBox@BoxLayout>:
    size_hint_y: None
    height: 30
    padding: (100, 0, 100, 0)
    Button:
        id: close_bt
        background_normal: "data/backgrounds/bt_process.png"
        background_down: "data/backgrounds/bt_process_off.png"
        bold: True
        text: "Close"
        on_release:
            root.cancel()

#===============================================================================
# CHECK ACTIONS
#===============================================================================

<CheckBt@Button>:
    background_normal: "data/backgrounds/bt_process.png"
    bold: True
    shorten: True
    shorten_from: "right"
    text_size: self.size
    halign: "center"
    valign: "middle"


<CheckDialog@BoxLayout>:
    orientation: "vertical"
    id: check
    text: None
    BoxLayout:
        padding: 10
        Label:
            valign: "middle"
            halign: "center"
            text_size: (self.size[0] - 5, self.size[1])
            id: check_text
    BoxLayout:
        size_hint_y: None
        height: 50
        spacing: 10
        padding: 10
        CheckBt:
            background_normal: "data/backgrounds/check_ok.png"
            background_down: "data/backgrounds/check_cancel.png"
            size_hint_x: 1
            text: "Yes"
            id: check_ok
            on_release:
                root.cancel()
        Button:
            id: check_cancel
            background_normal: "data/backgrounds/check_cancel.png"
            background_down: "data/backgrounds/check_ok.png"
            bold: True
            text: "No"
            on_release:
                root.cancel()

#===============================================================================
# WARNINGS
#===============================================================================

<WarningDialog@BoxLayout>:
    padding: 10
    orientation: "vertical"
    ScrollView:
        GridLayout:
            cols: 1
            padding: 10
            size_hint_y: None
            height: warning_l.texture_size[1] * 1.1

            Label:
                id: warning_l
                halign: "center"
                valign: "middle"
                size_hint: (1, None)
                text_size: self.width, None
                size: self.parent.width, self.texture_size[1]
                markup: True


    BoxLayout:
        size_hint_y: None
        height: 30
        padding: (150, 0, 150, 0)
        Button:
            background_normal: "data/backgrounds/check_ok.png"
            background_down: "data/backgrounds/check_cancel.png"
            text: "Close"
            id: close_bt
            bold: True
            on_release:
                root.cancel()

#===============================================================================
# ORTHOLOGY SCREEN
#===============================================================================

#===============================================================================
# ORTHOLOGY RESULT DESCRIPTION
#===============================================================================

<ExploreOpsBt@ToggleButton>:
    padding: 5,5
    border: 0,0,0,0
    group: "explore_bts"
    size_hint_x: None
    valign: "middle"
    text_size: self.size
    width: 100
    on_release:
        app.toggle_groups(self)

<DescriptionBox@BoxLayout>:
    orientation: "vertical"
    size_hint_y: None
    height: 520
    spacing: 10
    # Setting custom attributes
    prot_txt: ""
    taxa_txt: ""
    ortholog_txt: ""
    group_name: ""
    BoxLayout:
        orientation: "vertical"
        id: bx1
        size_hint_y: None
        height: 110
        padding: 10
        canvas.before:
            Color:
                rgba: (0.1, 0.1, 0.1, .5)
            Rectangle:
                pos: self.pos
                size: self.size
        StackLayout:
            canvas.after:
                Color:
                    rgb: (0.216, 0.67, 0.784, 1)
                Line:
                    width: 0.8
                    cap: "round"
                    joint: "round"
                    rectangle: bx1.x,bx1.y,bx1.width,bx1.height
        BoxLayout:
            size_hint_y: None
            height: 30
            Label:
                text: "General information"
                halign: "left"
                valign: "middle"
                text_size: self.size
                bold: True
            Label:
                text: root.group_name
                halign: "right"
                valign: "middle"
                text_size: self.size
                bold: True
                font_size: 20
                color: (0.216, 0.67, 0.784, 1)

        BoxLayout:
            size_hint_y: None
            height: 60
            BoxLayout:
                spacing: 10
                Vseparator:
                    thickness: 2
                BoxLayout:
                    orientation: "vertical"
                    DescriptionLabelLarge:
                        text: root.prot_txt
                    DescriptionLabelSmall:
                        text: "Proteins"
            BoxLayout:
                spacing: 10
                Vseparator:
                    thickness: 2
                BoxLayout:
                    orientation: "vertical"
                    DescriptionLabelLarge:
                        text: root.taxa_txt
                    DescriptionLabelSmall:
                        text: "Taxa"
            BoxLayout:
                spacing: 10
                Vseparator:
                    thickness: 2
                BoxLayout:
                    orientation: "vertical"
                    DescriptionLabelLarge:
                        text: root.ortholog_txt
                    DescriptionLabelSmall:
                        text: "Total orthologs"

    BoxLayout:
        id: filt_bx
        orientation: "vertical"
        size_hint_y: None
        #cols: 1
        height: 320
        padding: 10
        canvas.before:
            Color:
                rgba: (0.1, 0.1, 0.1, .5)
            Rectangle:
                pos: self.pos
                size: self.size
        StackLayout:
            canvas.after:
                Color:
                    rgb: (0.216, 0.67, 0.784, 1)
                Line:
                    width: 0.8
                    cap: "round"
                    joint: "round"
                    rectangle: filt_bx.x,filt_bx.y,filt_bx.width,filt_bx.height
        BoxLayout:
            size_hint_y: None
            height: 30
            Label:
                text: "Filtered orthologs"
                halign: "left"
                valign: "middle"
                text_size: self.size
                bold: True
            Widget
            TFButton:
                text: "Export as..."
                size_hint_x: None
                width: 100
                on_release:
                    app.dialog_export_groups()

        BoxLayout:
            size_hint_y: None
            height: 180
            id: gauge_bx
            #GaugePlot:
            #    proportion: 0.7
            #    ortholog_num: "47236"

        Widget:
            size_hint_y: None
            height: 10

        AnchorLayout:
            anchor_x: "center"
            anchor_y: "center"
            size_hint_y: None
            height: 60

            TFButton:
                size_hint: (None, None)
                size: 120, 30
                text: "Change filters"
                on_release:
                    app.dialog_orto_setfilter(root.group_name)

        BoxLayout:
            size_hint_y: None
            height: 20

            Label:
                color: .7, .7, .7, 1
                font_size: 12
                text: "Maximum gene copies: %s" % app.ortho_groups.get_group(root.group_name).gene_threshold if app.ortho_groups.get_group(root.group_name) else "None"
                bold: True
                halign: "left"
                valign: "middle"
                text_size: self.size
            Label:
                color: .7, .7, .7, 1
                font_size: 12
                text: "Minimum taxa representation: %s" % app.ortho_groups.get_group(root.group_name).species_threshold if app.ortho_groups.get_group(root.group_name) else "None"
                bold: True
                halign: "left"
                valign: "middle"
                text_size: self.size

<DescriptionLabelLarge@Label>:
    bold: True
    halign: "left"
    valign: "bottom"
    text_size: self.size
    font_size: 22
    size_hint_y: None
    height: 40
    color: (0.216, 0.67, 0.784, 1)

<DescriptionLabelSmall@Label>:
    bold: True
    halign: "left"
    valign: "top"
    text_size: self.size
    font_size: 12
    size_hint_y: None
    height: 20
    color: .7,.7,.7,1

<GaugePlot@BoxLayout>:
    orientation: "vertical"
    padding: 10
    spacing: 10
    txt: "After gene filter"
    proportion: 0
    ortholog_num: ""
    inner_color: {"After species filter": (0.16,0.16,0.16,1), "After gene filter": (0.14,0.14,0.14,1), "Final orthologs": (0.12,0.12,0.12,1)}
    Label:
        id: gauge_txt
        text: root.txt
        size_hint_y: None
        height: 30
        bold: True
        font_size: 14 if root.txt == "Final orthologs" else 12
    AnchorLayout:
        anchor_y: "center"
        anchor_x: "center"
        BoxLayout:
            size_hint: (None, None)
            size: 100,100
            canvas.before:
                Color:
                    rgba: (113/255, 200/255, 55/255, 1) if gauge_txt.text == "Final orthologs" else (.7,.7,.7,1)
                Ellipse:
                    size: self.size
                    pos: self.pos
                    angle_start: 360 - (root.proportion * 360)
                Color:
                    rgba: root.inner_color[gauge_txt.text] if gauge_txt.text in root.inner_color else (0,0,0,0)
                    #rgba: (0.15, 0.15, 0.15, 1)
                Ellipse:
                    size: 80, 80
                    pos: self.center_x - 40, self.center_y - 40
            BoxLayout:
                orientation: "vertical"
                Label:
                    bold: True
                    text: root.ortholog_num
                    color: (113/255, 200/255, 55/255, 1) if gauge_txt.text == "Final orthologs" else (.7,.7,.7,1)
                    font_size: 22
                    halign: "center"
                    valign: "bottom"
                    text_size: self.size
                    size_hint_y: .55
                Label:
                    bold: True
                    text: str(round(root.proportion * 100, 1)) + "%"
                    color: (113/255, 200/255, 55/255, 1) if gauge_txt.text == "Final orthologs" else (.7,.7,.7,1)
                    halign: "center"
                    valign: "top"
                    text_size: self.size
                    size_hint_y: .45


<MainSideBt@ToggleButton>:
    size_hint_y: None
    height: 80
    halign: "center"
    valign: "middle"
    text_size: self.size
    bold: True
    group: "orto_main"
    #background_color: (1,1,1,.7) if self.state == "normal" else (1,1,1,1)
    disabled_color: (0.216, 0.67, 0.784, 1)
    background_normal: "data/backgrounds/orto_sidebt.png"
    background_disabled_down: "data/backgrounds/orto_sidebt_down.png"
    on_release:
        app.toggle_groups(self)


<OrtoSetFiltersDialog@BoxLayout>:
    orientation: "vertical"
    spacing: 20
    padding: 10
    group_name: ""
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        AnchorLayout:
            size_hint_y: None
            height: 40
            anchor_x: "center"
            anchor_y: "center"
            BoxLayout:
                size_hint: None, None
                size: 250, 30
                Label:
                    text: "Apply filters to all group files"
                    size_hint_x: .9
                CheckBox:
                    id: apply_chk
                    active: True
                    size_hint_x: .1

        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 5
            Label:
                size_hint_x: .8
                text: "Maximum number of gene copies:"
                halign: "left"
                valign: "middle"
                text_size: self.size
            TextInput:
                id: gene_txt
                size_hint_x: .2
                text: str(app.ortho_groups.get_group(root.group_name).gene_threshold) if app.ortho_groups.get_group(root.group_name) else str(app.orto_max_gene)
        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 5
            Label:
                size_hint_x: .8
                text: "Minimum number of taxa:"
                halign: "left"
                valign: "middle"
                text_size: self.size
            TextInput:
                id: sp_txt
                size_hint_x: .2
                text: str(app.ortho_groups.get_group(root.group_name).species_threshold) if app.ortho_groups.get_group(root.group_name) else str(app.orto_min_sp)

    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 10
        Button:
            id: ok_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Ok"
            bold: True
            on_release:
                app.orto_change_filters(gene_txt.text, sp_txt.text, group_name=root.group_name, apply_all=apply_chk.active)
                app.orthology_card(app.ortho_groups.get_group(root.group_name))
                root.cancel()
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Cancel"
            bold: True
            on_release:
                root.cancel()

<PlotOpt@SpinnerOption>:
    bold: True
    size_hint_y: None
    height: 30
    background_normal: "data/backgrounds/spinner_opt.png"

<PlotSpinner@Spinner>:
    bold: True
    border: 0,0,0,0
    background_normal: "data/backgrounds/plot_spinner.png"
    size_hint: None, None
    size: 180, 33
#===============================================================================
# ORTHOLOGY EXECUTION DIALOG
#===============================================================================

<OrtoExecutionDialog@BoxLayout>:
    padding: 10
    orientation: "vertical"
    spacing: 10
    BoxLayout:
        orientation: "vertical"
        padding: 10
        ExecLabel:
            id: gene_filter
        ExecLabel:
            id: sp_filter
        ExecLabel:
            id: eval
        ExecLabel:
            id: inflation
        ExecLabel:
            id: threads

    Label:
        size_hint_y:None
        height: 30
        bold: True
        text: "[color=37abc8ff]Do you want to proceed?[/color]"
        markup: True
    BoxLayout:
        size_hint_y: None
        height: 40
        padding: (50, 0, 50, 0)
        spacing: 20
        Button:
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Execute"
            id: ok_bt
            bold: True
            on_release:
                root.cancel()
                app.orthology_search_exec()

        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Cancel"
            bold: True
            on_release:
                root.cancel()


<OrtoProgressDialog@BoxLayout>:
    padding: 10
    orientation: "vertical"
    proc_kill: False

    Label:
        id: msg
        bold: True

    ProgressBar:
        max: 10
        id: pb

    BoxLayout:
        size_hint_y: None
        height: 30
        AnchorLayout:
            anchor_x: "center"
            anchor_y: "center"
            Button:
                id: close_bt
                size_hint_x: None
                width: 150
                background_normal: "data/backgrounds/bt_process.png"
                background_down: "data/backgrounds/bt_process_off.png"
                text: "Cancel"
                bold: True
                on_release:
                    root.proc_kill = True

<OrthoGraphicReport@BoxLayout>:
    padding: 10
    spacing: 10
    orientation: "vertical"
    inf: None
    BoxLayout:
        size_hint_y: None
        height: 50
        spacing: 5
        orientation: "vertical"
        Label:
            bold: True
            text: "Total orthologs"
            halign: "left"
            valign: "middle"
            text_size: self.size
            color: (.7,.7,.7,1)
        BoxLayout:
            canvas.before:
                Color:
                    rgba: (.7,.7,.7,1)
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                bold: True
                id: total_ort

    BoxLayout:
        size_hint_y: None
        height: 50
        spacing: 5
        orientation: "vertical"
        Label:
            bold: True
            text: "After gene filter"
            halign: "left"
            valign: "middle"
            text_size: self.size
            color: (.7,.7,.7,1)
        BoxLayout:
            BoxLayout:
                id: gf_box
                canvas.before:
                    Color:
                        rgba: (.7,.7,.7,1)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    id: gf_txt
                    bold: True

            BoxLayout
                size_hint_x: 1 - gf_box.size_hint_x
                canvas.before:
                    Color:
                        rgba: (.4, .4, .4, 1)
                    Rectangle:
                        pos: self.pos
                        size: self.size

    BoxLayout:
        size_hint_y: None
        height: 50
        spacing: 5
        orientation: "vertical"
        Label:
            bold: True
            text: "After species filter"
            halign: "left"
            valign: "middle"
            text_size: self.size
            color: (.7,.7,.7,1)
        BoxLayout
            BoxLayout:
                id: sf_box
                canvas.before:
                    Color:
                        rgba: (.7,.7,.7,1)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    bold: True
                    id: sf_txt
            BoxLayout
                size_hint_x: 1 - sf_box.size_hint_x
                canvas.before:
                    Color:
                        rgba: (.4, .4, .4, 1)
                    Rectangle:
                        pos: self.pos
                        size: self.size

    BoxLayout:
        size_hint_y: None
        height: 80
        spacing: 5
        orientation: "vertical"
        Label:
            bold: True
            text: "Final Orthologs"
            halign: "center"
            valign: "middle"
            text_size: self.size
            color: (113/255, 200/255, 55/255, 1)
        BoxLayout:
            BoxLayout:
                id: final_box
                canvas.before:
                    Color:
                        rgba: (113/255, 200/255, 55/255, 1)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Label:
                    bold: True
                    id: final_txt
            BoxLayout
                size_hint_x: 1 - final_box.size_hint_x
                canvas.before:
                    Color:
                        rgba: (.4, .4, .4, 1)
                    Rectangle:
                        pos: self.pos
                        size: self.size

<OrthoReportDialog@BoxLayout>:
    padding: 10
    orientation: "vertical"
    spacing: 10
    BoxLayout:
        size_hint_y: None
        height: 50
        AnchorLayout:
            padding: 5
            anchor_x: "left"
            anchor_y: "center"
            size_hint_x: None
            width: 50
            Button:
                background_normal: "data/backgrounds/prev_car.png"
                background_down: "data/backgrounds/prev_car_down.png"
                on_release:
                    report_car.load_previous()
        AnchorLayout:
            anchor_x: "center"
            anchor_y: "center"
            Label:
                bold: True
                text: "Inflation value %s" % report_car.current_slide.inf if report_car.current_slide else "Waaaa?"
        AnchorLayout:
            padding: 5
            anchor_x: "right"
            anchor_y: "center"
            size_hint_x: None
            width: 50
            Button:
                background_normal: "data/backgrounds/next_car.png"
                background_down: "data/backgrounds/next_car_down.png"
                on_release:
                    report_car.load_next()

    BoxLayout:
        padding: 10
        Carousel:
            id: report_car

    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 10
        Button:
            id: ok_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Go to Restuls"
            bold: True
            on_release:
                app.screen.ids.explore_bt.dispatch("on_release")
                app.screen.ids.explore_bt.state = "down"
                root.cancel()
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Close"
            bold: True
            on_release:
                root.cancel()

<OrtoReportBox@BoxLayout>:
    orientation: "vertical"
    ExecLabel:
        id: total_orts
    ExecLabel:
        id: genet_orts
    ExecLabel:
        id: spt_orts
    ExecLabel:
        id: twot_orts

<OrtoFilterDialog>:
    orientation: "vertical"
    spacing: 20
    padding: 10
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 5
            Label:
                size_hint_x: .8
                text: "Maximum number of gene copies:"
                halign: "left"
                valign: "middle"
                text_size: self.size
            TextInput:
                id: gene_txt
                size_hint_x: .2
                text: str(app.orto_max_gene)
        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 5
            Label:
                size_hint_x: .8
                text: "Minimum number of taxa:"
                halign: "left"
                valign: "middle"
                text_size: self.size
            TextInput:
                id: sp_txt
                size_hint_x: .2
                text: str(app.orto_min_sp)

    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 10
        Button:
            id: ok_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Ok"
            bold: True
            on_release:
                app.save_ortho_filters(gene_txt.text, sp_txt.text)
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Cancel"
            bold: True
            on_release:
                root.cancel()

<InflationDialog>:
    orientation: "vertical"
    spacing: 10
    padding: 10
    BoxLayout:
        size_hint_y: None
        height: 30
        spacing: 10
        Label:
            size_hint_x: .6
            text: "Select one or more inflation values:"
            halign: "left"
            valign: "middle"
            text_size: self.size

    BoxLayout:
        id: inflation_bx
        size_hint_y: None
        height: 30
        ToggleButton:
            text: "1.5"
        ToggleButton:
            text: "2"
        ToggleButton:
            state: "down"
            text: "3"
        ToggleButton:
            text: "4"
        ToggleButton:
            text: "5"

    Widget:
        size_hint_y: None
        height: 10

    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 10
        Button:
            id: ok_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Ok"
            bold: True
            on_release:
                app.save_inflation(inflation_bx)
                root.cancel()
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Cancel"
            bold: True
            on_release: root.cancel()

<MySQLDialog>:
    orientation: "vertical"
    padding: 10
    spacing: 10
    TextInput:
        id: txt_dlg
        password: True
        focus: True
    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 10
        Button:
            id: ok_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Ok"
            bold: True
            on_release:
                app.save_mysql_pass(txt_dlg.text)
                root.cancel()
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Cancel"
            bold: True
            on_release: root.cancel()

<ProteinFilterDialog>:
    padding: 10
    spacing: 10
    orientation: "vertical"
    BoxLayout:
        size_hint_y: None
        height: 30
        Label:
            size_hint_x: .7
            text: "Minimum sequence length:"
        TextInput:
            size_hint_x: .3
            id: txt_len
            text: str(app.protein_min_len)
    BoxLayout:
        size_hint_y: None
        height: 30
        Label:
            size_hint_x: .7
            text: "Maximum codon stops (%):"
        TextInput
            size_hint_x: .3
            id: txt_stop
            text: str(app.protein_max_stop)
    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 10
        Button:
            id: ok_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Ok"
            bold: True
            on_release:
                app.save_protein_filters(txt_len.text, txt_stop.text)
                root.cancel()
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Cancel"
            bold: True
            on_release: root.cancel()

<OrthologySearchGrid@TabbedPanel>:
    do_default_tab: False
    tab_pos: "top_left"
    background_color: (0,0,0,0)
    opacity: 0

    TabbedPanelItem:
        id: main_tab
        text: "Filtering"

        GridLayout:
            id: protein_filter
            cols: 1
            padding: 5
            spacing: 5

            LightBox:
                Label:
                    markup: True
                    text: "[size=15][b]Sequence quality control[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Filter protein sequences[/b][/size]\n[size=13]Set filters to remove poor quality sequences based on sequence length and stop codon percentage.[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                BoxLayout:
                    #padding: (0, 7.5, 0, 7.5)
                    size_hint_x: .2
                    ProcessBt:
                        text: "Set filters"
                        on_release:
                            app.dialog_protein_filter()

    TabbedPanelItem:
        id: partition_tab
        text: "USEARCH"

        GridLayout:
            id: usearch_tab
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    markup: True
                    text: "[size=15][b]USEARCH options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Database name[/b][/size]\n[size=13]Name of the database against which USEARCH will run.[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                ProcessBt:
                    size_hint_x: .2
                    text: app.usearch_db
                    id: db_bt
                    on_release:
                        app.dialog_text("USEARCH database", "usearch_db")

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]USEARCH output file[/b][/size]\n[size=13]Name of the file containing the search results of USEARCH.[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                ProcessBt:
                    size_hint_x: .2
                    text: app.usearch_output
                    id: out_bt
                    on_release:
                        app.dialog_text("USEARCH output file", "usearch_out")

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]E-value cutoff[/b][/size]\n[size=13](default: AllVsAll.out)Set minimum necessary e-value cutoff to retain USEARCH hits.[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                ProcessBt:
                    size_hint_x: .2
                    text: app.usearch_evalue
                    id: eval
                    on_release:
                        app.dialog_text("E-value cutoff value", "evalue")

    TabbedPanelItem:
        id: mcl_tab
        text: "MCL"

        GridLayout:
            id: mcl_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    markup: True
                    text: "[size=15][b]MCL options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Inflation[/b][/size]\n[size=13]Set one or more inflation values for MCL run.[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                ProcessBt:
                    size_hint_x: .2
                    id: inflation_bt
                    text: "['3']"
                    on_release:
                        app.dialog_inflation()

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Ortholog group prefix[/b][/size]\n[size=13]Set a prefix name for the ortholog groups detected by OrthoMCL.[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                ProcessBt:
                    size_hint_x: .2
                    text: app.ortholog_prefix
                    id: orto_group
                    on_release:
                        app.dialog_text("Prefix for ortholog groups", "orto_group")

            Hseparator

            DarkBox:
                height: 70
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Groups file[/b][/size]\n[size=13]Set the name for the final output of OrthoMCL containing the ortholog groups. If more than one inflation values were specified, this name will be used as a prefix[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                BoxLayout:
                    size_hint_x: .2
                    padding: (0, 7.5, 0, 7.5)
                    ProcessBt:
                        text: app.group_prefix
                        id: group_prefix
                        on_release:
                            app.dialog_text("Groups file name", "groups")

<LoadMultipleDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        spacing: 10
        padding: 10

        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 10
            Label:
                padding: (5, 0)
                canvas.before:
                    Color:
                        rgba: .35, .35, .35, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: sd_filechooser.path
                halign: "left"
                valign: "middle"
                text_size: self.size
            Button:
                bold: True
                size_hint_x: None
                width: 100
                text: "New folder"
                background_normal: "data/backgrounds/bt_process.png"
                background_down: "data/backgrounds/bt_process_off.png"
                on_release:
                    app.dialog_text("New folder", "new_folder")

        FileChooserM:
            id: sd_filechooser
            text: "master"
            multiselect: True
            path: app.home_path

        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 20
            padding: (150, 0, 150, 0)

            Button:
                background_normal: "data/backgrounds/bt_process.png"
                background_down: "data/backgrounds/bt_process_off.png"
                text: "Save"
                id: ok_bt
                bold: True
                on_release:
                    if sd_filechooser.selection:\
                    app.run_in_background(app.load_group_files, app.load_groups, [sd_filechooser.selection], None)
                    #root.cancel()

            Button:
                background_normal: "data/backgrounds/bt_process_off.png"
                background_down: "data/backgrounds/bt_process.png"
                id: cancel_bt
                text: "Cancel"
                bold: True
                on_release: root.cancel()

#===============================================================================
# PROCESS EXECUTION SUMMARY
#===============================================================================

<ExecLabel@Label>:
    halign: "left"
    valign: "middle"
    text_size: self.size
    markup: True
    font_size: 16

<ExecutionDialog@BoxLayout>:
    padding: 10
    orientation: "vertical"
    spacing: 10
    BoxLayout:
        padding: 10
        orientation: "vertical"
        ExecLabel:
            id: main_op
        ExecLabel:
            id: sec_op
        ExecLabel:
            id: out_form
        ExecLabel:
            id: out_files
    Label:
        size_hint_y:None
        height: 30
        bold: True
        text: "[color=37abc8ff]Do you want to proceed?[/color]"
        markup: True
    BoxLayout:
        size_hint_y: None
        height: 40
        padding: (50, 0, 50, 0)
        spacing: 20
        Button:
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Execute"
            id: ok_bt
            bold: True
            on_release:
                app.process_exec()
                root.cancel()
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Cancel"
            bold: True
            on_release:
                root.cancel()

<DoneDialog@BoxLayout>:
    orientation: "vertical"
    id: check
    text: None
    BoxLayout:
        padding: 10
        Label:
            canvas.before:
                Color:
                    rgba: (.2, .2, .2, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size
            valign: "middle"
            halign: "center"
            text_size: (self.size[0] - 5, self.size[1])
            text: "All done!"
    BoxLayout:
        size_hint_y: None
        height: 30
        padding: (30, 0, 30, 0)
        Button:
            id: close_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Close"
            bold: True
            on_release:
                root.cancel()

#===============================================================================
# TAXA GROUP CREATION
#===============================================================================

<TaxaGroupDialog@BoxLayout>:
    orientation: "vertical"
    padding: 10
    spacing: 10
    ds_type: ""
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        BoxLayout:
            size_hint_y: .1
            BoxLayout:
                spacing: 10
                Label:
                    text: "Set group name:"
                    bold: True
                    size_hint_x: .2
                    text_size: self.size
                    halign: "left"
                    valign: "middle"
                TextInput:
                    size_hint_x: .8
                    id: group_name
                    text: "untitled_1"
                    multiline: False

        BoxLayout:
            BoxLayout:
                orientation: "vertical"
                Label:
                    canvas.before:
                        Color:
                            rgba: .2, .2, .2, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    text: "Selected taxa" if root.ds_type == "taxa" else "Selected files"
                    size_hint_y: None
                    height: 40
                    bold: True
                Hseparator
                ScrollView:
                    bar_width: 10
                    scroll_type: ["bars", "content"]
                    canvas.before:
                        Color:
                            rgba: .3, .3, .3, .5
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    GridLayout:
                        id: select_grid
                        cols:1
                        size_hint_y: None
                        height: 0
                Widget:
                    size_hint_y: None
                    height: 15

            BoxLayout:
                orientation: "vertical"
                size_hint_x: .30
                spacing: 10
                BoxLayout:
                    padding: 20
                    spacing: 20
                    orientation: "vertical"
                    Button:
                        background_down: "data/backgrounds/tg_addall.png"
                        background_normal: "data/backgrounds/tg_addall_down.png"
                        size_hint: (None, None)
                        size: (47,50)
                        border: (0,0,0,0)
                        on_release:
                            app.taxagroup_move_taxa(root.ids.all_grid, root.ids.select_grid, True, root.ds_type)
                    Button:
                        background_down: "data/backgrounds/tg_add.png"
                        background_normal: "data/backgrounds/tg_add_down.png"
                        size_hint: (None, None)
                        size: (47,50)
                        on_release:
                            app.taxagroup_move_taxa(root.ids.all_grid, root.ids.select_grid, False, root.ds_type)
                    Button:
                        background_down: "data/backgrounds/tg_remove.png"
                        background_normal: "data/backgrounds/tg_remove_down.png"
                        size_hint: (None, None)
                        size: (47,50)
                        on_release:
                            app.taxagroup_move_taxa(root.ids.select_grid, root.ids.all_grid, False, root.ds_type)
                    Button:
                        background_down: "data/backgrounds/tg_removeall.png"
                        background_normal: "data/backgrounds/tg_removeall_down.png"
                        size_hint: (None, None)
                        size: (47,50)
                        on_release:
                            app.taxagroup_move_taxa(root.ids.select_grid, root.ids.all_grid, True, root.ds_type)
                Widget:
                    size_hint_y: .05
            BoxLayout:
                orientation: "vertical"
                Label:
                    canvas.before:
                        Color:
                            rgba: .2, .2, .2, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    text: "All taxa" if root.ds_type == "taxa" else "All files"
                    size_hint_y: None
                    height: 40
                    bold: True
                Hseparator
                ScrollView:
                    bar_width: 10
                    scroll_type: ["bars", "content"]
                    canvas.before:
                        Color:
                            rgba: .3, .3, .3, .5
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    GridLayout:
                        id: all_grid
                        cols:1
                        size_hint_y: None
                        height: 0
                Widget:
                    size_hint_y: None
                    height: 15
        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 20
            Button:
                background_normal: "data/backgrounds/bt_process.png"
                background_down: "data/backgrounds/bt_process_off.png"
                id: ok_bt
                font_size: 16
                text: "Ok"
                bold: True
                on_release:
                    # Check for empty selected group
                    if not select_grid.children: \
                    app.dialog_floatcheck("ERROR: Cannot create an empty data set group", t="error")
                    # Check for duplicate group name for taxa and file dialogs
                    elif root.ds_type == "taxa" and root.ids.group_name.text in app.taxa_groups: \
                    app.dialog_floatcheck("ERROR: Cannot create a data set group with a duplicate name. Please use a different name.", t="error")
                    elif root.ds_type == "files" and root.ids.group_name.text in app.file_groups: \
                    app.dialog_floatcheck("ERROR: Cannot create a data set group with a duplicate name. Please use a different name.", t="error")
                    # Save group and quit dialog
                    if root.ds_type == "taxa" and select_grid.children and root.ids.group_name.text not in app.taxa_groups: \
                    app.save_dataset_group(root.ids.select_grid, root.ids.group_name.text, root.ds_type); root.cancel()
                    if root.ds_type == "files" and select_grid.children and root.ids.group_name.text not in app.file_groups: \
                    app.save_dataset_group(root.ids.select_grid, root.ids.group_name.text, root.ds_type); root.cancel()

            Button:
                background_normal: "data/backgrounds/bt_process_off.png"
                background_down: "data/backgrounds/bt_process.png"
                id: apply_bt
                font_size: 16
                text: "Apply"
                bold: True
                on_release:
                    # Check for empty selected group
                    if not select_grid.children: \
                    app.dialog_floatcheck("ERROR: Cannot create an empty data set group", t="error")
                    # Check for duplicate group name for taxa and file dialogs
                    elif root.ds_type == "taxa" and root.ids.group_name.text in app.taxa_groups: \
                    app.dialog_floatcheck("ERROR: Cannot create a data set group with a duplicate name. Please use a different name.", t="error")
                    elif root.ds_type == "files" and root.ids.group_name.text in app.file_groups: \
                    app.dialog_floatcheck("ERROR: Cannot create a data set group with a duplicate name. Please use a different name.", t="error")
                    # Save group
                    if root.ds_type == "taxa" and select_grid.children and root.ids.group_name.text not in app.taxa_groups: \
                    app.save_dataset_group(root.ids.select_grid, root.ids.group_name.text, root.ds_type)
                    if root.ds_type == "files" and select_grid.children and root.ids.group_name.text not in app.file_groups: \
                    app.save_dataset_group(root.ids.select_grid, root.ids.group_name.text, root.ds_type)
            Button:
                background_normal: "data/backgrounds/bt_process_off.png"
                background_down: "data/backgrounds/bt_process_off.png"
                id: cancel_bt
                font_size: 16
                text: "Cancel"
                bold: True
                on_release:
                    root.cancel()

#===============================================================================
# GENERAL SAVE FILE
#===============================================================================

<SaveDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        spacing: 10
        padding: 10

        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 10
            Label:
                padding: (5, 0)
                canvas.before:
                    Color:
                        rgba: .35, .35, .35, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size
                text: sd_filechooser.path
                halign: "left"
                valign: "middle"
                text_size: self.size
            Button:
                bold: True
                size_hint_x: None
                width: 100
                text: "New folder"
                background_normal: "data/backgrounds/bt_process.png"
                background_down: "data/backgrounds/bt_process_off.png"
                on_release:
                    app.dialog_text("New folder", "new_folder")

        FileChooserL:
            id: sd_filechooser
            text: "master"
            path: app._common_path() if app._common_path() else app.home_path
            #on_selection: text_input.text = self.selection

        BoxLayout:
            id: txt_box
            orientation: "horizontal"
            size_hint_y: None
            height: 30
            Label:
                size_hint_x: None
                width: 100
                text: "File name:"
            TextInput:
                id: text_input
                multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 20
            padding: (150, 0, 150, 0)

            Button:
                background_normal: "data/backgrounds/bt_process.png"
                background_down: "data/backgrounds/bt_process_off.png"
                text: "Save"
                id: ok_bt
                bold: True
                text_io: text_input.text if not None else ""
                on_release:
                    # For save dialogs requiring file name, make this check
                    if self.text_io == "" and txt_box.height == 30: \
                    app.dialog_floatcheck(text="WARNING: Please provide a file name", t="error")
                    # For save dialogs requiring a file name, save the file name
                    elif self.text_io != "" and sd_filechooser.text == "main_output" and txt_box.height == 30: \
                    app.save_file(sd_filechooser.path, file_name = text_input.text, idx = sd_filechooser.text)
                    elif self.text_io != "" and sd_filechooser.text == "export": \
                    app.export_names(sd_filechooser.path, file_name = text_input.text)
                    elif self.text_io != "" and sd_filechooser.text == "export_table": \
                    app.export_table(sd_filechooser.path, text_input.text)
                    elif self.text_io != "" and sd_filechooser.text == "group": \
                    app.orto_export_groups("group", output_dir=sd_filechooser.path, output_name=text_input.text)

                    # For save dialogs that do not require file names
                    elif sd_filechooser.text == "main_output" and txt_box.height == 0: \
                    app.save_file(sd_filechooser.path, idx = sd_filechooser.text)
                    elif sd_filechooser.text == "ortho_dir" and txt_box.height == 0: \
                    app.save_file(sd_filechooser.path, idx = sd_filechooser.text)
                    elif sd_filechooser.text == "protein_db" and txt_box.height == 0: \
                    app.save_file(sd_filechooser.selection, idx=sd_filechooser.text)
                    elif sd_filechooser.text == "orto_export_dir" and txt_box.height == 0: \
                    app.save_file(sd_filechooser.path, idx=sd_filechooser.text)
                    elif sd_filechooser.text == "protein" or sd_filechooser.text == "nucleotide": \
                    app.orto_export_groups(sd_filechooser.text, output_dir=sd_filechooser.path)
                    # Close dialog
                    if self.text_io != "" or txt_box.height == 0 and sd_filechooser.text != "protein" and sd_filechooser.text != "nucleotide" and sd_filechooser.text != "group": root.cancel()

            Button:
                background_normal: "data/backgrounds/bt_process_off.png"
                background_down: "data/backgrounds/bt_process.png"
                id: cancel_bt
                bold: True
                text: "Cancel"
                on_release: root.cancel()

#===============================================================================
# ACTION BAR HEADERS
#===============================================================================

<MainHeader@ActionToggleButton>:
    size_hint_x: 1
    font_size: 20
    bold: True
    group: "main_header"
    disabled_color: (1, 1, 1, 1)

#===============================================================================
# SIDE PANEL WIDGETS
#===============================================================================

<SelectionBox@BoxLayout>:
    orientation: "horizontal"
    size_hint_y: None
    height: 35
    spacing: 20
    Button:
        text: "Select All"
        disabled: True
    Button:
        text: "Deselect All"
        disabled: True

<SideButton@ToggleButton>:
    group: "side_buttons"
    size_hint_y: .1
    font_size: 30
    bold: True
    disabled_color: (1,1,1,1)
    border: (0,0,0,0)

<LoadMoreBt@AnchorLayout>:
    anchor_x: "left"
    Widget:
        size_hint_y:None
        height: 50
    Button:
        text: "Load next 20"
        size_hint_x: None
        width: 260
        background_normal: "data/backgrounds/main_op_bt.png"
        background_down: "data/backgrounds/bt_sideprocess.png"
        on_release:
            app.sidepanel_load_more_filebts()

#===============================================================================
#                               PROCESS SCREEN
#===============================================================================

<ExecutionBt@Button>
    background_normal: "data/backgrounds/process_exec.png"
    background_down: "data/backgrounds/process_exec_down.png"
    border: 0,0,0,0
    bold: True
    halign: "center"
    valign: "middle"
    text_size: self.size
    font_size: 18
    color: (1,1,1,1)
    size_hint_y: None
    height: 45

#===============================================================================
# PARTITIONS
#===============================================================================

<DetailLabel@Label>:
    size_hint_y: None
    height: 30
    halign: "left"
    valign: "middle"
    text_size: self.size
    markup: True

<FieldLabel@Label>:
    size_hint_y: None
    height: 30
    bold: True
    halign: "left"
    valign: "top"
    text_size: self.size
    color: (0.216, 0.67, 0.784, 1)

<CodonSpinner@SpinnerOption>:
    markup: True
    bold: True
    on_release:
        app.set_codon_model(self.text)

<ModelSpinner@Spinner>:
    bold: True
    text: "JC"
    values: ("JC", "F81", "K2P", "HKY", "SYM", "GTR")
    #background_normal: "data/backgrounds/model_bt1.png"

<PartitionsDialog@BoxLayout>:
    id: partition_wgt
    padding: [30, 10, 10, 10]
    orientation: "vertical"
    spacing: 10

    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            source: "data/backgrounds/codon_background.png"
            pos: self.pos
            size: self.size
    BoxLayout:
        size_hint_y: None
        height: 60
        orientation: "vertical"
        FieldLabel:
            text: "Codon partitions"
        Spinner:
            id: codon_spin
            text: "No partition"
            markup: True
            bold: True
            option_cls: Factory.get("CodonSpinner")
            values: ("No partitions", "[color=ff5555ff]1[/color] + [color=37abc8ff]2[/color] + [color=71c837ff]3[/color]", "[color=ff5555ff](1 + 2)[/color] + [color=37abc8ff]3[/color]", "[color=ff5555ff]1[/color] + [color=37abc8ff](2 + 3)[/color]", "[color=ff5555ff](1 + 3)[/color] + [color=37abc8ff]2[/color]")

    BoxLayout:
        size_hint_y: None
        height: 60
        orientation: "vertical"
        id: model_bx
        FieldLabel:
            text: "Substitution model"
        BoxLayout:
            spacing: 5
            id: model_bx
            ModelSpinner

    BoxLayout:
        size_hint_y: None
        height: 20
        spacing: 10
        AnchorLayout:
            Button:
                size_hint_x: None
                width: 100
                text: "Save"
                bold: True
                background_normal: "data/backgrounds/bt_process.png"
                background_down: "data/backgrounds/bt_process_off.png"

#===============================================================================
# PROCESS OUTPUT FORMAT
#===============================================================================

<SettingsBt@Button>:
    size_hint_x: None
    width: 40
    disabled: True
    background_normal: "data/backgrounds/settings.png"
    background_down: "data/backgrounds/settings_down.png"
    background_disabled_normal: "data/backgrounds/settings_disabled.png"
    #Image:
    #    source: "data/backgrounds/settings.png"
    #    pos: self.parent.x, self.parent.y
    #    #x: self.parent.x
    #    size: 40, 40
    #    allow_stretch: True

<FormatDialog>:
    padding: [30, 20, 30, 20]
    spacing: 25
    orientation: "vertical"
    id: format_dlg
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10
            ToggleButton:
                background_normal: "data/backgrounds/bt_process_off.png"
                background_down: "data/backgrounds/bt_process.png"
                id: fasta
                state: "down"
                text: "Fasta"
            SettingsBt
        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10
            ToggleButton:
                background_normal: "data/backgrounds/bt_process_off.png"
                background_down: "data/backgrounds/bt_process.png"
                id: phylip
                text: "Phylip"
            SettingsBt:
                disabled: False
                on_release:
                    app.dialog_phylip_extra()
        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10
            ToggleButton:
                background_normal: "data/backgrounds/bt_process_off.png"
                background_down: "data/backgrounds/bt_process.png"
                id: nexus
                text: "Nexus"
            SettingsBt:
                disabled: False
                on_release:
                    app.dialog_nexus_extra()
        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10
            ToggleButton:
                background_normal: "data/backgrounds/bt_process_off.png"
                background_down: "data/backgrounds/bt_process.png"
                id: mcmctree
                text: "MCMCTree"
            SettingsBt
        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10
            ToggleButton:
                background_disabled_normal: "data/backgrounds/bt_process_disabled.png"
                id: ima2
                text: "IMa2"
                disabled: True
            SettingsBt
    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: 30
        spacing: 10
        padding: (10, 0, 10, 0)
        Button:
            id: ok_bt
            text: "Ok"
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            bold: True
            on_release: app.save_format(format_dlg)
        Button:
            id: cancel_bt
            text: "Cancel"
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            bold: True
            on_release: root.cancel()

<NexusExtra@BoxLayout>:
    padding: 10
    spacing: 10
    orientation: "vertical"
    BoxLayout:
        Label:
            text: "Write the partitions block, if any."
        CheckBox:
            id: nexus_check
            size_hint_x: .2

    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 20
        Button:
            id: ok_bt
            text: "Ok"
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            bold: True
            on_release:
                app.use_nexus_partitions = root.ids.nexus_check.active
                app.dismiss_subpopup()
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            bold: True
            text: "Cancel"
            on_release: root.cancel()

<PhylipExtra@BoxLayout>:
    padding: 10
    spacing: 10
    orientation: "vertical"
    BoxLayout:
        Label:
            text: "Create partition file when concatenating"
        CheckBox:
            id: part_check
            size_hint_x: .2

    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 20
        Button:
            id: ok_bt
            text: "Ok"
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            bold: True
            on_release:
                app.create_partfile = root.ids.part_check.active
                app.dismiss_subpopup()
        Button:
            id: cancel_bt
            text: "Cancel"
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            bold: True
            on_release: root.cancel()

#===============================================================================
# PROCESS FORMATTING ADDITIONAL OPTIONS
#===============================================================================

<ZorroDialog>:
    orientation: "vertical"
    padding: 10
    spacing: 15
    Switch:
        id: zorro_switch
    BoxLayout:
        spacing: 10
        size_hint_y: None
        height: 30
        Label:
            valign: "middle"
            halign: "left"
            text_size: self.size
            size_hint_x: .5
            text: "ZORRO files suffix:"
            bold: True
        TextInput:
            id: zorro_txt
            multiline: False
            size_hint_x: .5

    BoxLayout:
        orientation: "horizontal"
        spacing: 10
        Button:
            id: ok_bt
            text: "Ok"
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            bold: True
            on_release: app.save_zorro_settings(zorro_txt.text)
        Button:
            id: cancel_bt
            text: "Cancel"
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            bold: True
            on_release: root.cancel()

#===============================================================================
# PROCESS HAPLOTYPE ADDITIONAL OPTIONS
#===============================================================================

<TextDialog>:
    orientation: "vertical"
    padding: 10
    spacing: 10
    idx: None
    TextInput:
        id: txt_dlg
        focus: True
    BoxLayout:
        size_hint_y: None
        height: 30
        orientation: "horizontal"
        spacing: 10
        Button:
            id: ok_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Ok"
            bold: True
            on_release:
                if root.text == "new_folder": \
                app.create_folder(txt_dlg.text)
                else: \
                app.save_text(txt_dlg.text, root.text)
                root.cancel()
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Cancel"
            bold: True
            on_release: root.cancel()

#===============================================================================
# REVERSE CONCATENATION OPTIONS
#===============================================================================

<InputList@BoxLayout>:
    orientation: "vertical"
    spacing: 10
    padding: 10
    ScrollView:
        GridLayout:
            spacing: 5
            cols: 1
            id: rev_inlist
            size_hint_y: None
            height: sum([x.height + 5 for x in self.children])

    AnchorLayout:
        size_hint_y: None
        height: 30
        BoxLayout:
            size_hint_x: None
            width: 180
            spacing: 10
            Button:
                size_hint_x: None
                width: 80
                id: ok_bt
                text: "Ok"
                bold: True
                background_normal: "data/backgrounds/bt_process.png"
                background_down: "data/backgrounds/bt_process_off.png"
                on_release:
                    root.cancel()
            Button:
                size_hint_x: None
                width: 80
                id: cancel_bt
                text: "Cancel"
                bold: True
                background_normal: "data/backgrounds/bt_process_off.png"
                background_down: "data/backgrounds/bt_process.png"
                on_release:
                    root.cancel()

<LoadDialog>
    orientation: "vertical"
    spacing: 10
    padding: 10
    Label:
        size_hint_y: None
        text: ld_filechooser.path
        height: 30
        text_size: (self.size[0] - 20, self.size[1])
        shorten: True
        shorten_from: "left"
        halign: "center"
        valign: "middle"
        canvas.before:
            Color:
                rgba: .35, .35, .35, 1
            Rectangle:
                pos: self.pos
                size: self.size

    FileChooserListView:
        id: ld_filechooser
        f: "/*"
        filters: [self.path+self.f]
        filter_dirs: True

    BoxLayout:
        size_hint_y: None
        height: 30
        spacing: 5

        Label:
            canvas.before:
                Color:
                    rgba: (.2,.2,.2,1)
                Rectangle:
                    pos: self.pos
                    size: self.size
            size_hint_x: .15
            text: "Find:"
            bold: True
        ToggleButton:
            id: case_bt
            text: "Aa"
            bold:True
            size_hint_x: .1
            state: "down"

        TextInput:
            id: text_filter
            multiline: False
            focus: True
            on_text:
                if case_bt.state == "down": ld_filechooser.f = "*"+"".join(["["+x.upper()+x.lower()+"]" for x in self.text])+"*"
                if case_bt.state == "normal": ld_filechooser.f = "*"+self.text+"*"

            on_text_validate:
                focus = True

    BoxLayout:
        size_hint_y: None
        height: 35
        spacing: 10

        Button:
            id: ok_bt
            text: "OK"
            bold: True
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            on_release:
                app.save_reverseconc_partfile(ld_filechooser.selection[0])
                root.cancel()
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            bold: True
            text: "Cancel"
            on_release: root.cancel()

<RevConcDialog>:
    orientation: "vertical"
    spacing: 30
    padding: 10

    BoxLayout:
        size_hint_y: .8
        #height: 50
        spacing: 10
        orientation: "vertical"

        Switch:
            id: rev_conc
            on_active:
                if self.active == True: app.update_main_operations("reverse_concatenation"); rev_infile.disabled = False; part_file.disabled = False
                if self.active == False: app.update_main_operations("concatenation"); rev_infile.disabled = True; part_file.disabled = True

        Button:
            id: part_file
            background_normal: "data/backgrounds/bt_process_off.png"
            background_disabled_normal: "data/backgrounds/bt_process_disabled.png"
            halign: "center"
            valign: "middle"
            shorten: True
            shorten_from: "left"
            text_size: self.size
            text: "Select partition file"
            disabled: True
            on_release:
                app.dialog_load_partfile()

        Button:
            id: rev_infile
            background_normal: "data/backgrounds/bt_process_off.png"
            background_disabled_normal: "data/backgrounds/bt_process_disabled.png"
            text: "Select file to reverse concatenate"
            halign: "center"
            valign: "middle"
            shorten: True
            shorten_from: "left"
            text_size: self.size
            disabled: True
            on_release:
                app.dialog_reverse_inlist()

    BoxLayout:
        size_hint_y: None
        height: 30
        spacing: 10
        padding: (30, 0, 30, 0)
        Button:
            id: ok_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "OK"
            bold: True
            on_release:
                if rev_conc.active: \
                app.save_reverseconc_settings()
                else: \
                root.cancel()

        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Cancel"
            bold: True
            on_release: root.cancel()

#===============================================================================
# PROCESS FILTER ADDITIONAL OPTIONS
#===============================================================================

<FilterDialog>:
    orientation: "vertical"
    padding: 20
    spacing: 20

    Label:
        text: "Gap threshold"
        bold: True
        halign: "left"
        valign: "middle"
        text_size: self.size

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: 30
        spacing: 20
        Slider:
            id: gap_sli
            size_hint_x: .85
            min: 0
            max: 100
            step: 1
            value: 25
        TextInput:
            size_hint_x: .15
            id: gap_ti
            text: "{}".format(round(gap_sli.value))
            multiline: False
            on_text_validate: if app.check_filters(gap_ti.text): gap_sli.value = app.check_filters(gap_ti.text)[1]

    Label:
        text: "Missing data threshold"
        bold: True
        halign: "left"
        valign: "middle"
        text_size: self.size

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: 30
        spacing: 20
        Slider:
            id: mis_sli
            size_hint_x: .85
            min: 0
            max: 100
            step: 1
            value: 50
        TextInput:
            size_hint_x: .15
            id: mis_ti
            text: "{}".format(round(mis_sli.value))
            multiline: False
            on_text_validate: if app.check_filters(mis_ti.text): mis_sli.value = app.check_filters(mis_ti.text)[1]

    BoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: 30
        spacing: 10
        Button:
            id: ok_bt
            background_normal: "data/backgrounds/bt_process.png"
            background_down: "data/backgrounds/bt_process_off.png"
            text: "Ok"
            bold: True
            on_release: app.save_filter(gap_sli.value, mis_sli.value)
        Button:
            id: cancel_bt
            background_normal: "data/backgrounds/bt_process_off.png"
            background_down: "data/backgrounds/bt_process.png"
            text: "Cancel"
            bold: True
            on_release: root.cancel()

<Sidebt@ToggleButton>:
    #background_color: [0,0,0,1]
    size_hint_y: None
    height: 50
    background_normal: "data/backgrounds/main_op_bt.png"
    background_down: "data/backgrounds/bt_sideprocess.png"
    background_disabled_down: "data/backgrounds/bt_sideprocess.png"
    disabled_color: (1, 1, 1, 1)
    halign: "center"
    valign: "middle"
    text_size: self.size
    bold: True
    font_size: 18
    padding: (20, 0)

# Vertical light grey separator
<Vseparator@Widget>:
    size_hint_x: None
    width: self.thickness + 2 * self.margin
    thickness: 1
    margin: 1
    canvas:
        Color:
            rgb: .5, .5, .5
        Rectangle:
            pos: self.x + self.margin + 1, self.y + self.margin + 10
            size: self.thickness, self.height - 2 * self.margin - 20

<LightBox@BoxLayout>:
    height: 40
    orientation: "horizontal"
    size_hint_y: None
    padding: 10
    canvas.before:
        Color:
            rgba: (.3, .3, .3, .8)
        Rectangle:
            pos: self.pos
            size: self.size

<DarkBox@BoxLayout>:
    height: 55
    orientation: "horizontal"
    size_hint_y: None
    padding: 5

<Hseparator@Widget>:
    size_hint_y: None
    height: self.thickness + 2 * self.margin
    thickness: 1
    margin: 1
    canvas:
        Color:
            rgb: .5, .5, .5
        Rectangle:
            pos: self.x + self.margin, self.y + self.margin +1
            size: self.width - 2 * self.margin, self.thickness

<ProcessBt@Button>:
    background_normal: "data/backgrounds/bt_process.png"
    size_hint_x: .2
    bold: True
    shorten: True
    shorten_from: "right"
    text_size: self.size
    halign: "center"
    valign: "middle"

#===============================================================================
# PROCESS GENERAL OPTIONS
#===============================================================================

<ProcessGeneral@GridLayout>:
    id: main_grid
    padding: (5,5)
    cols: 1
    size_hint_y: None
    height: sum([x.size[1] for x in self.children])
    opacity: 0
    __safe_id: [taxa_dropdown.__self__, file_dropdown.__self__]
    LightBox:
        Label:
            markup: True
            text: "[size=15][b]General[/b][/size]"
            halign: "left"
            valign: "middle"
            color: [.85, .85, .85, 1]
            text_size: self.size

    DarkBox:
        Label:
            size_hint_x: .74
            markup: True
            text: "[size=18][b]Data set[/b][/size]\n[size=13]Select the active taxa data set to perform operations[/size]"
            halign: "left"
            valign: "middle"
            text_size: self.size
        InfoBt:
            width: 50
            height: 50
            height:
            on_release:
                app.dialog_general_info("process_dataset")

        BoxLayout:
            spacing: 5
            size_hint_x: .2

            ProcessBt:
                id: active_file_set
                text: "All files"
                on_release: file_dropdown.open(self)

            ProcessBt:
                id: active_taxa_set
                text: "All taxa"
                on_release: taxa_dropdown.open(self)

            DropDown:
                id: taxa_dropdown
                auto_width: False
                size_hint_x: None
                width: 170
                on_select: active_taxa_set.text = args[1]
                canvas.before:
                    Color:
                        rgba: (0,0,0,1)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Widget:
                    size_hint_y: None
                    height: 3
                ProcessBt:
                    background_color: (1,1,1,.3)
                    text: 'All taxa'
                    size_hint_y: None
                    height: 40
                    on_release: taxa_dropdown.select(self.text)
                Widget:
                    size_hint_y: None
                    height: 3
                ProcessBt:
                    background_color: (1,1,1,.3)
                    text: 'Active taxa'
                    size_hint_y: None
                    height: 40
                    on_release: taxa_dropdown.select(self.text)

            DropDown:
                id: file_dropdown
                auto_width: False
                size_hint_x: None
                width: 170
                on_select: active_file_set.text = args[1]
                canvas.before:
                    Color:
                        rgba: (0,0,0,1)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                Widget:
                    size_hint_y: None
                    height: 3
                ProcessBt:
                    background_color: (1,1,1,.3)
                    text: 'All files'
                    size_hint_y: None
                    height: 40
                    on_release: file_dropdown.select(self.text)
                Widget:
                    size_hint_y: None
                    height: 3
                ProcessBt:
                    background_color: (1,1,1,.3)
                    text: 'Active files'
                    size_hint_y: None
                    height: 40
                    on_release: file_dropdown.select(self.text)

    Hseparator

    DarkBox:
        Label:
            size_hint_x: .8
            markup: True
            text: "[size=18][b]Output Format[/b][/size]\n[size=13]Choose the format of the output file(s). Multiple formats may be chosen[/size]"
            halign: "left"
            valign: "middle"
            text_size: self.size
        ProcessBt:
            id: conv_formatbt
            text: "%s" % app.output_formats[0].title() if len(app.output_formats) == 1 else "%s selected" % len(app.output_formats)
            on_release: app.dialog_format()
    Hseparator

    DarkBox:
        id: dark_l
        Label:
            id: output_label
            size_hint_x: .8
            markup: True
            text: "[size=18][b]Output file[/b][/size]\n[size=13]Save output file to...[/size]"
            halign: "left"
            valign: "middle"
            text_size: self.size
        ProcessBt:
            id: conv
            text: "Select..."
            on_release: app.dialog_filechooser("main_output")

    BoxLayout:
        size_hint_y: None
        height: 60
        AnchorLayout:
            Button:
                bold: True
                id: opt_bt
                text: "Show additional options"
                size_hint: None, None
                width: 300
                height: 40
                on_release:
                    app.toggle_process_options()

#===============================================================================
# PROCESS ADDITIONAL OPTIONS
#===============================================================================

<AdditionalProcessContents@TabbedPanel>:
    do_default_tab: False
    tab_pos: "top_left"
    background_color: (0,0,0,0)
    opacity: 0

    TabbedPanelItem:
        id: main_tab
        text: "Formatting"

        GridLayout:
            id: main_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    markup: True
                    text: "[size=15][b]Formatting options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Interleave[/b][/size]\n[size=13]If sequences should be in interleave format or leave"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                Switch:
                    id: interleave
                    size_hint_x: .2
                    on_active:
                        app.update_process_switch("interleave", self.active)

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .74
                    markup: True
                    text: "[size=18][b]ZORRO weights support[/b][/size]\n[size=13]Concatenation only. Concatenates auxiliary Zorro weight files into a single *_zorro.out file."
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                InfoBt:
                    width: 50
                    height: 50
                    on_release:
                        app.dialog_general_info("zorro")
                ProcessBt:
                    id: zorro
                    background_normal: "data/backgrounds/bt_process_off.png"
                    size_hint_x: .2
                    text: "OFF"
                    disabled: False if app.main_operations["concatenation"] else True
                    on_release:
                        if app.active_file_list: \
                        app.dialog_zorro()
                        else: \
                        app.dialog_floatcheck("ERROR: No input files have been selected to use this option", t="error")

    TabbedPanelItem:
        id: partition_tab
        text: "Partitions"

        GridLayout:
            id: partition_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    markup: True
                    text: "[size=15][b]Partitioning options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    id: test2
                    text: "[size=18][b]Change/View partitions[/b][/size]\n[size=13] General options for viewing, adding or removing partitions [/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                ProcessBt:
                    id: part_dialog
                    text: "Select..."
                    disabled: True

    TabbedPanelItem:
        id: collapse_tab
        text: "Collapse"

        GridLayout:
            id: collapse_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    size_hint_x: .77
                    markup: True
                    text: "[size=15][b]Sequence collapsing options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size
                InfoBt:
                    width: 20
                    height: 20
                    background_normal: "data/backgrounds/more_info_20px.png"
                    background_down: "data/backgrounds/more_info_down_20px.png"
                    on_release:
                        app.dialog_general_info("collapse")
                Switch:
                    size_hint_x: .2
                    id: collapse
                    on_active:
                        if self.active == True: root.ids.hapbt.disabled = False; root.ids.collapse_file.disabled = False
                        if self.active == False: root.ids.hapbt.disabled = True; root.ids.collapse_file.disabled = True
                        app.update_process_switch("collapse", self.active)

            DarkBox:
                height: 70
                Label:
                    size_hint_x: .8
                    markup: True
                    id: test2
                    text: "[size=18][b]Save in new output file[/b][/size]\n[size=13] If checked, the collapsed alignments will be saved in a file with an '_haplotype' suffix in addition to the main output file[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                CheckBox:
                    id: collapse_file
                    size_hint_x: .2
                    disabled: True
                    on_active:
                        app.update_process_switch("collapse_file", self.active)

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    id: test2
                    text: "[size=18][b]Haplotype prefix[/b][/size]\n[size=13] Select the prefix name for the haplotypes [/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                ProcessBt:
                    size_hint_x: .2
                    id: hapbt
                    disabled: True
                    text: "Hap"
                    on_release:
                        app.dialog_text("Haplotype prefix", "haplotype")

    TabbedPanelItem:
        id: filter_tab
        text: "Filter"

        GridLayout:
            id: filter_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    size_hint_x: .77
                    markup: True
                    text: "[size=15][b]Sequence filter options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size
                InfoBt:
                    width: 20
                    height: 20
                    background_normal: "data/backgrounds/more_info_20px.png"
                    background_down: "data/backgrounds/more_info_down_20px.png"
                    on_release:
                        app.dialog_general_info("filter")
                Switch:
                    id: filter
                    size_hint_x: .2
                    on_active:
                        if self.active == True: root.ids.cv_filterbt.disabled = False; root.ids.filter_file.disabled = False
                        if self.active == False: root.ids.cv_filterbt.disabled = True; root.ids.filter_file.disabled = True
                        app.update_process_switch("filter", self.active)

            DarkBox:
                height: 70
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Save in new output file[/b][/size]\n[size=13] If checked, the filtered alignments will be saved in a file with an '_filtered' suffix in addition to the main output file[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                CheckBox:
                    id: filter_file
                    size_hint_x: .2
                    disabled: True
                    on_active:
                        app.update_process_switch("filter_file", self.active)

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    id: test2
                    text: "[size=18][b]Gap/Missing data filter[/b][/size]\n[size=13] Set filters to remove alignment columns with excessive gap and/or missing data [/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                ProcessBt:
                    id: cv_filterbt
                    disabled: True
                    text: "Set filters"
                    on_release: app.dialog_filter()

    TabbedPanelItem:
        id: gcoder_tab
        text: "Gcoder"

        GridLayout:
            id: gcoder_grid
            cols: 1
            padding: 5
            spacing: 5
            opacity: 1

            LightBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=15][b]Gap coding options[/b][/size]"
                    halign: "left"
                    valign: "middle"
                    color: [.85, .85, .85, 1]
                    text_size: self.size
                Switch:
                    id: gcoder
                    size_hint_x: .2
                    disabled: True if app.output_formats != ["nexus"] else False
                    on_active:
                        if self.active == True: root.ids.gcoder_file.disabled = False
                        if self.active == False: root.ids.gcoder_file.disabled = True
                        app.update_process_switch("gcoder", self.active)

            DarkBox:
                height: 70
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Save in new output file[/b][/size]\n[size=13] If checked, the coded alignments will be saved in a file with an '_coded' suffix in addition to the main output file[/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                CheckBox:
                    id: gcoder_file
                    size_hint_x: .2
                    disabled: True
                    on_active:
                        app.update_process_switch("gcoder_file", self.active)

            Hseparator

            DarkBox:
                Label:
                    size_hint_x: .8
                    markup: True
                    text: "[size=18][b]Gap coding method[/b][/size]\n[size=13] Choose the coding method [/size]"
                    halign: "left"
                    valign: "middle"
                    text_size: self.size
                ProcessBt:
                    id: gcode_bt
                    disabled: True
                    text: "Choose..."

#===============================================================================
# ROOT SCREEN
#===============================================================================

FloatLayout:
    __safe_id: [file_dd.__self__, taxa_dd.__self__]
    BoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: (.7,.7,.7,1)
            Rectangle:
                source: "data/backgrounds/master_background.jpg"
                pos: self.pos
                size: self.size

        ActionBar:
            pos_hint: {'top':1}

            ActionView:
                id: av
                ActionPrevious:
                    id: ap
                    size_hint_x: None
                    app_icon: "data/backgrounds/app_icon.png"
                    background_normal: "data/backgrounds/menu_bt.png"
                    background_down: "data/backgrounds/menu_bt_down.png"
                    border: (0,0,0,0)
                    width: 120
                    #title: "Menu"
                    with_previous: False
                    on_release:
                        app.toggle_sidepanel()

                MainHeader:
                    id: h_ortho
                    text: "Orthology"
                    background_down: "data/backgrounds/orthology_down.png"
                    background_disabled_down: "data/backgrounds/orthology_down.png"
                    canvas.before:
                        Color:
                            rgba: [255, .200, .200, .3]
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    on_release:
                        idx = app.screen_names.index("Orthology")
                        app.go_screen(idx)
                        app.toggle_groups(self)

                MainHeader:
                    id: h_process
                    text: "Process"
                    background_down: "data/backgrounds/process_down.png"
                    background_disabled_down: "data/backgrounds/process_down.png"
                    canvas.before:
                        Color:
                            rgba: (0.200, 0.200, 255, .3)
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    on_release:
                        idx = app.screen_names.index("Process")
                        app.go_screen(idx)
                        app.toggle_groups(self)

                MainHeader:
                    id: h_stat
                    text: "Statistics"
                    background_down: "data/backgrounds/statistics_down.png"
                    background_disabled_down: "data/backgrounds/statistics_down.png"
                    canvas.before:
                        Color:
                            rgba: (0.200, 255, 0.200, .3)
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    on_release:
                        idx = app.screen_names.index("Statistics")
                        app.go_screen(idx)
                        app.toggle_groups(self)

        BoxLayout:
            id: bx1
            orientation: "horizontal"

            # This BoxLayout will two ScrollView layouts.
            # The first will be the side column with several buttons that will
            # switch the content in the second scrollview layout
            # The second will be the main panel containing the important content
            FloatLayout:
                id: panel_float
                size_hint_x: None
                BoxLayout:
                    orientation: "horizontal"
                    id: main_box
                    size_hint_x: None
                    width: 0
                    canvas.before:
                        Color:
                            rgb: (.2, .2, .2)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    # Both these ScrollView layouts are here because it is the only way
                    # that the children layouts' width will be truly 0. If a
                    # BoxLayout, Floatlayout, etc would be used, the contents would
                    # still appear.
                    ScrollView:
                        id: sp_bts
                        size_hint_x: None
                        width: 0
                        BoxLayout:
                            id: side_bt
                            orientation: "vertical"
                            SideButton:
                                size_hint: (None, None)
                                height: 60
                                width: 60
                                text: " "
                                background_down: "data/backgrounds/side_bt_home_down.png"
                                background_normal: "data/backgrounds/side_bt_home.png"
                                background_disabled_down: "data/backgrounds/side_bt_home_down.png"
                                att: "Open/View Data"
                                state: "down"
                                disabled: True
                                on_release:
                                    carousel.load_slide(carousel.slides[0])
                                    app.toggle_groups(self)
                            SideButton:
                                size_hint: (None, None)
                                height: 60
                                width: 60
                                text: " "
                                background_down: "data/backgrounds/side_bt_group_down.png"
                                background_normal: "data/backgrounds/side_bt_group.png"
                                background_disabled_down: "data/backgrounds/side_bt_group_down.png"
                                att: "Dataset Groups"
                                on_release:
                                    carousel.load_slide(carousel.slides[1])
                                    app.toggle_groups(self)
                            SideButton:
                                size_hint: (None, None)
                                height: 60
                                width: 60
                                text: " "
                                background_down: "data/backgrounds/side_bt_queue_down.png"
                                background_normal: "data/backgrounds/side_bt_queue.png"
                                background_disabled_down: "data/backgrounds/side_bt_queue_down.png"
                                id: queue
                                att: "Operations Queue"
                                on_release:
                                    app.save_operation_queue()
                                    carousel.load_slide(carousel.slides[2])
                                    app.toggle_groups(self)
                            Widget:
                                size_hint_y: .8
                                canvas.before:
                                    Color:
                                        rgba: (0.180, 0.180, 0.180, .8)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                    BoxLayout:
                        id: sp

                        Carousel:
                            id: carousel
                            direction: "bottom"
                            BoxLayout:
                                orientation: "vertical"
                                padding: 10
                                spacing: 10
                                id: main_slide

                                canvas.before:
                                    Color:
                                        rgba: (0.180, 0.180, 0.180, .8)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                                BoxLayout:
                                    size_hint_y: None
                                    height: 50
                                    padding: (15,0,15, 0)
                                    Button:
                                        id: sv_but
                                        background_normal: "data/backgrounds/process_exec.png"
                                        background_down: "data/backgrounds/process_exec_down.png"
                                        text: "Open file(s)"
                                        bold: True
                                        border: 0,0,0,0
                                        font_size: 18
                                        on_release:
                                            idx = app.screen_names.index("fc")
                                            app.go_screen(idx)
                                            app.toggle_sidepanel()

                                TabbedPanel:
                                    id: main_tp
                                    do_default_tab: False
                                    background_color: (0,0,0,0)
                                    tab_pos: "top_mid"
                                    tab_width: 90

                                    TabbedPanelItem:
                                        id: file_tp
                                        text: "Files"

                                        BoxLayout:
                                            orientation: "vertical"
                                            spacing: 10
                                            Widget:
                                                size_hint_y: None
                                                height: 0
                                            BoxLayout:
                                                size_hint_y: None
                                                height: 30
                                                AnchorLayout:
                                                    BoxLayout:
                                                        size_hint_x: None
                                                        width: 200
                                                        canvas.before:
                                                            Color:
                                                                rgba: 0.8, 0.8, 0.8, 1
                                                            Rectangle:
                                                                pos: self.pos
                                                                size: self.size
                                                        Button:
                                                            size_hint_x: None
                                                            width: 30
                                                            background_normal: "data/backgrounds/search_bt.png"
                                                            background_down: "data/backgrounds/search_bt.png"
                                                            on_release:
                                                                if file_search.text == "": \
                                                                app.sidepanel_clear_search("files")
                                                                else: \
                                                                app.sidepanel_search_bts(file_search.text, "files")
                                                        TextInput:
                                                            size_hint_x: None
                                                            width: 140
                                                            id: file_search
                                                            background_color: (1, 1, 1, 0)
                                                            foreground_color: (.1, .1, .1, .51)
                                                            hint_text: "Search files..."
                                                            multiline: False
                                                            on_text_validate:
                                                                if self.text == "": \
                                                                app.sidepanel_clear_search("files")
                                                                else: \
                                                                app.sidepanel_search_bts(self.text, "files")
                                                        Button:
                                                            size_hint_x: None
                                                            width: 30
                                                            background_normal: "data/backgrounds/clear_bt.png"
                                                            background_down: "data/backgrounds/clear_bt.png"
                                                            on_release:
                                                                app.sidepanel_clear_search("files")
                                                                file_search.text = ""
                                            ScrollView:
                                                id: sv_file
                                                GridLayout:
                                                    cols: 3
                                                    size_hint_y: None
                                                    id: file_sl
                                                    padding: (10, 0, 10, 0)
                                                    spacing: 5
                                                    height: sum([x.height + 5 for x in self.children]) / 3

                                                    Button:
                                                        id: file_temp
                                                        height: 40
                                                        disabled: True
                                                        size_hint_y: None
                                                        #size_hint_x: None
                                                        text: "No files loaded"
                                            Label:
                                                id: file_lab
                                                size_hint_y: None
                                                height: 10
                                                color: (.6, .6, .6, 1)
                                            BoxLayout:
                                                id: bt_bar_file
                                                spacing: 5
                                                size_hint_y: None
                                                height: 35
                                                BoxLayout:
                                                    id: sb_file
                                                    spacing: 5
                                                    Button:
                                                        text: "Select All"
                                                        disabled: True if not app.file_list and not app.proteome_files else False
                                                        background_normal: "data/backgrounds/bt_process_off.png"
                                                        background_down: "data/backgrounds/bt_process.png"
                                                        background_disabled_normal: "data/backgrounds/bt_process_disabled.png"
                                                        on_release:
                                                            app.select_bt(self)
                                                    Button:
                                                        text: "Deselect All"
                                                        disabled: True if not app.file_list and not app.proteome_files else False
                                                        background_normal: "data/backgrounds/bt_process_off.png"
                                                        background_down: "data/backgrounds/bt_process.png"
                                                        background_disabled_normal: "data/backgrounds/bt_process_disabled.png"
                                                        on_release:
                                                            app.select_bt(self)
                                                Button:
                                                    id: file_opt
                                                    text: "+"
                                                    font_size: 30
                                                    bold: True
                                                    size_hint_x: .18
                                                    disabled: True if not app.file_list and not app.proteome_files else False
                                                    background_normal: "data/backgrounds/bt_process_off.png"
                                                    background_down: "data/backgrounds/bt_process.png"
                                                    background_disabled_normal: "data/backgrounds/bt_process_disabled.png"
                                                    on_release:
                                                        file_dd.open(self)
                                                Button:
                                                    id: rm_all_file
                                                    size_hint_x: None
                                                    width: 35
                                                    disabled: True if not app.file_list and not app.proteome_files else False
                                                    background_normal: "data/backgrounds/remove_all.png"
                                                    background_down: "data/backgrounds/remove_all_down.png"
                                                    background_disabled_normal: "data/backgrounds/remove_all_disabled.png"
                                                    on_release:
                                                        app.check_action(text="Are you sure you want to remove all files and taxa?", func=app.remove_all)
                                                DropDown:
                                                    id: file_dd
                                                    auto_width: False
                                                    size_hint_x: None
                                                    width: 250
                                                    Button:
                                                        text_size: self.size
                                                        halign: "left"
                                                        valign: "middle"
                                                        size_hint: (None, None)
                                                        width: 250
                                                        height: 30
                                                        text: "  Export all file names as text"
                                                        on_release:
                                                            app.dialog_filechooser("export")
                                                            app.export_mode = ("file", "all")
                                                            file_dd.dismiss()
                                                    Button:
                                                        text_size: self.size
                                                        halign: "left"
                                                        valign: "middle"
                                                        size_hint: (None, None)
                                                        width: 250
                                                        height: 30
                                                        text: "  Export selected file names as text"
                                                        on_release:
                                                            app.dialog_filechooser("export")
                                                            app.export_mode = ("file", "selected")
                                                            file_dd.dismiss()
                                    TabbedPanelItem:
                                        id: taxa_tp
                                        text: "Taxa"
                                        BoxLayout:
                                            orientation: "vertical"
                                            spacing: 10
                                            Widget:
                                                size_hint_y: None
                                                height: 0
                                            BoxLayout:
                                                size_hint_y: None
                                                height: 30
                                                AnchorLayout:
                                                    BoxLayout:
                                                        size_hint_x: None
                                                        width: 200
                                                        canvas.before:
                                                            Color:
                                                                rgba: 0.8, 0.8, 0.8, 1
                                                            Rectangle:
                                                                pos: self.pos
                                                                size: self.size
                                                        Button:
                                                            size_hint_x: None
                                                            width: 30
                                                            background_normal: "data/backgrounds/search_bt.png"
                                                            background_down: "data/backgrounds/search_bt.png"
                                                            on_release:
                                                                if taxa_search.text == "": \
                                                                app.sidepanel_clear_search("taxa")
                                                                else: \
                                                                app.sidepanel_search_bts(taxa_search.text, "taxa")
                                                        TextInput:
                                                            size_hint_x: None
                                                            width: 140
                                                            id: taxa_search
                                                            background_color: (1, 1, 1, 0)
                                                            foreground_color: (.1, .1, .1, .51)
                                                            hint_text: "Search taxa..."
                                                            multiline: False
                                                            on_text_validate:
                                                                if self.text == "": \
                                                                app.sidepanel_clear_search("taxa")
                                                                else: \
                                                                app.sidepanel_search_bts(self.text, "taxa")
                                                        Button:
                                                            size_hint_x: None
                                                            width: 30
                                                            background_normal: "data/backgrounds/clear_bt.png"
                                                            background_down: "data/backgrounds/clear_bt.png"
                                                            on_release:
                                                                app.sidepanel_clear_search("taxa")
                                                                taxa_search.text = ""
                                            ScrollView:
                                                id: sv_sp
                                                GridLayout:
                                                    cols: 3
                                                    size_hint_y: None
                                                    id: taxa_sl
                                                    padding: (10, 0, 10, 0)
                                                    spacing: 5
                                                    height: sum([x.height + 5 for x in self.children]) / 3
                                                    Button:
                                                        id: species_temp
                                                        height: 40
                                                        disabled: True
                                                        size_hint_y: None
                                                        text: "No species loaded"
                                            Label:
                                                id: sp_lab
                                                size_hint_y: None
                                                height: 10
                                                color: (.6, .6, .6, 1)
                                            BoxLayout:
                                                spacing: 5
                                                size_hint_y: None
                                                height: 35
                                                BoxLayout:
                                                    id: sb_taxa
                                                    spacing: 5
                                                    Button:
                                                        text: "Select All"
                                                        disabled: True if not app.file_list else False
                                                        background_normal: "data/backgrounds/bt_process_off.png"
                                                        background_down: "data/backgrounds/bt_process.png"
                                                        background_disabled_normal: "data/backgrounds/bt_process_disabled.png"
                                                        on_release:
                                                            app.select_bt(self)
                                                    Button:
                                                        text: "Deselect All"
                                                        disabled: True if not app.file_list else False
                                                        background_normal: "data/backgrounds/bt_process_off.png"
                                                        background_down: "data/backgrounds/bt_process.png"
                                                        background_disabled_normal: "data/backgrounds/bt_process_disabled.png"
                                                        on_release:
                                                            app.select_bt(self)
                                                Button:
                                                    id: taxa_opt
                                                    text: "+"
                                                    font_size: 30
                                                    bold: True
                                                    size_hint_x: .18
                                                    disabled: True if not app.file_list else False
                                                    background_normal: "data/backgrounds/bt_process_off.png"
                                                    background_down: "data/backgrounds/bt_process.png"
                                                    background_disabled_normal: "data/backgrounds/bt_process_disabled.png"
                                                    on_release:
                                                        taxa_dd.open(self)
                                                Button:
                                                    id: rm_all_taxa
                                                    size_hint_x: None
                                                    width: 35
                                                    disabled: True if not app.file_list else False
                                                    background_normal: "data/backgrounds/remove_all.png"
                                                    background_down: "data/backgrounds/remove_all_down.png"
                                                    background_disabled_normal: "data/backgrounds/remove_all_disabled.png"
                                                    on_release:
                                                        app.check_action("Are you sure you want to remove all files and taxa?", app.remove_all)
                                                DropDown:
                                                    id: taxa_dd
                                                    auto_width: False
                                                    size_hint_x: None
                                                    width: 250
                                                    Button:
                                                        text_size: self.size
                                                        halign: "left"
                                                        valign: "middle"
                                                        size_hint: (None, None)
                                                        width: 250
                                                        height: 30
                                                        text: " Export all taxa names as text"
                                                        on_release:
                                                            app.dialog_filechooser("export")
                                                            app.export_mode = ("taxa", "all")
                                                            taxa_dd.dismiss()
                                                    Button:
                                                        text_size: self.size
                                                        halign: "left"
                                                        valign: "middle"
                                                        size_hint: (None, None)
                                                        width: 250
                                                        height: 30
                                                        text: " Export selected taxa names as text"
                                                        on_release:
                                                            app.dialog_filechooser("export")
                                                            app.export_mode = ("taxa", "selected")
                                                            taxa_dd.dismiss()

                                    TabbedPanelItem:
                                        id: partitions_tp
                                        text: "Partitions"

                                        BoxLayout:
                                            orientation: "vertical"
                                            spacing: 10
                                            Widget:
                                                size_hint_y: None
                                                height: 0
                                            BoxLayout:
                                                size_hint_y: None
                                                height: 30
                                                AnchorLayout:
                                                    BoxLayout:
                                                        size_hint_x: None
                                                        width: 200
                                                        canvas.before:
                                                            Color:
                                                                rgba: 0.8, 0.8, 0.8, 1
                                                            Rectangle:
                                                                pos: self.pos
                                                                size: self.size
                                                        Button:
                                                            size_hint_x: None
                                                            width: 30
                                                            background_normal: "data/backgrounds/search_bt.png"
                                                            background_down: "data/backgrounds/search_bt.png"
                                                            on_release:
                                                                if file_search.text == "": \
                                                                app.sidepanel_clear_search("partitions")
                                                                else: \
                                                                app.sidepanel_search_bts(file_search.text, "partitions")

                                                        TextInput:
                                                            size_hint_x: None
                                                            width: 140
                                                            id: partition_search
                                                            background_color: (1, 1, 1, 0)
                                                            foreground_color: (.1, .1, .1, .51)
                                                            hint_text: "Search partitions..."
                                                            multiline: False
                                                            on_text_validate:
                                                                if self.text == "": \
                                                                app.sidepanel_clear_search("partitions")
                                                                else: \
                                                                app.sidepanel_search_bts(self.text, "partitions")

                                                        Button:
                                                            size_hint_x: None
                                                            width: 30
                                                            background_normal: "data/backgrounds/clear_bt.png"
                                                            background_down: "data/backgrounds/clear_bt.png"
                                                            on_release:
                                                            on_release:
                                                                app.sidepanel_clear_search("partitions")
                                                                partition_search.text = ""
                                            ScrollView:
                                                id: sv_partition
                                                GridLayout:
                                                    cols: 3
                                                    size_hint_y: None
                                                    id: partition_sl
                                                    padding: (10, 0, 10, 0)
                                                    spacing: 5
                                                    height: sum([x.height + 5 for x in self.children]) / 3

                                                    Button:
                                                        id: partition_temp
                                                        height: 40
                                                        disabled: True
                                                        size_hint_y: None
                                                        #size_hint_x: None
                                                        text: "No partitions loaded"
                                            Label:
                                                id: partition_lab
                                                size_hint_y: None
                                                height: 10
                                                color: (.6, .6, .6, 1)
                                            BoxLayout:
                                                id: bt_bar_partition
                                                spacing: 5
                                                size_hint_y: None
                                                height: 35
                                                BoxLayout:
                                                    id: sb_partition
                                                    spacing: 5
                                                    Button:
                                                        text: "Select All"
                                                        disabled: True
                                                        background_normal: "data/backgrounds/bt_process_off.png"
                                                        background_down: "data/backgrounds/bt_process.png"
                                                        background_disabled_normal: "data/backgrounds/bt_process_disabled.png"
                                                    Button:
                                                        text: "Deselect All"
                                                        disabled: True
                                                        background_normal: "data/backgrounds/bt_process_off.png"
                                                        background_down: "data/backgrounds/bt_process.png"
                                                        background_disabled_normal: "data/backgrounds/bt_process_disabled.png"

                            BoxLayout:
                                orientation: "vertical"
                                padding: 10
                                spacing: 5
                                canvas.before:
                                    Color:
                                        rgba: (0.180, 0.180, 0.180, .8)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                                Label:
                                    size_hint_y: .1
                                    text: "Dataset groups"
                                    font_size: 18
                                    halign: "center"
                                    valign: "middle"
                                    text_size: self.size
                                    bold: True
                                    canvas.before:
                                        Color:
                                            rgba: .35, .35, .35, 1
                                        Rectangle:
                                            pos: self.pos
                                            size: self.size

                                Hseparator

                                TabbedPanel:
                                    id: dataset_tp
                                    do_default_tab: False
                                    background_color: (0,0,0,0)
                                    tab_pos: "top_mid"

                                    TabbedPanelItem:
                                        id: file_ds_tp
                                        text: "Files"
                                        BoxLayout:
                                            orientation: "vertical"
                                            spacing: 20
                                            ScrollView:
                                                size_hint_y: .8
                                                GridLayout:
                                                    id: file_group_grid
                                                    size_hint_y: None
                                                    height: 0
                                                    padding: 5
                                                    spacing: 5
                                                    cols: 2

                                            BoxLayout:
                                                size_hint_y: None
                                                height: 40
                                                padding: (50, 0, 50, 0)
                                                Button:
                                                    bold: True
                                                    text: "Set new file group"
                                                    id: file_group_bt
                                                    disabled: True if not app.file_list else False
                                                    background_normal: "data/backgrounds/bt_process.png"
                                                    background_down: "data/backgrounds/bt_process_off.png"
                                                    on_release:
                                                        app.dialog_taxagroup("files")

                                    TabbedPanelItem:
                                        id: taxa_ds_tp
                                        text: "Taxa"

                                        BoxLayout:
                                            orientation: "vertical"
                                            spacing: 20
                                            ScrollView:
                                                size_hint_y: .8
                                                GridLayout:
                                                    id: taxa_group_grid
                                                    size_hint_y: None
                                                    height: 0
                                                    padding: 5
                                                    spacing: 5
                                                    cols: 2

                                            BoxLayout:
                                                size_hint_y: None
                                                height: 40
                                                padding: (50, 0, 50, 0)
                                                Button:
                                                    bold: True
                                                    text: "Set new taxa group"
                                                    id: tx_group_bt
                                                    disabled: True if not app.file_list else False
                                                    background_normal: "data/backgrounds/bt_process.png"
                                                    background_down: "data/backgrounds/bt_process_off.png"
                                                    on_release:
                                                        app.dialog_taxagroup("taxa")

                            BoxLayout:
                                orientation: "vertical"
                                padding: 10
                                spacing: 5
                                canvas.before:
                                    Color:
                                        rgba: (0.180, 0.180, 0.180, .8)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                                Label:
                                    size_hint_y: .1
                                    text: "Operations queue"
                                    font_size: 18
                                    halign: "center"
                                    valign: "middle"
                                    text_size: self.size
                                    bold: True
                                    canvas.before:
                                        Color:
                                            rgba: .35, .35, .35, 1
                                        Rectangle:
                                            pos: self.pos
                                            size: self.size
                                Hseparator
                                ScrollView:
                                    size_hint_y: .8
                                    id: op_sv
                                Widget:
                                    size_hint_y: .1


            ScreenManager:
                id: sm

