<Sidebt@ToggleButton>:
    #background_color: [0,0,0,1]
    size_hint_y: None
    height: 70
    background_normal: "data/backgrounds/bt_sideprocess_normal.png"
    background_down: "data/backgrounds/bt_sideprocess.png"
    halign: "left"
    valign: "middle"
    text_size: self.size
    bold: True
    font_size: 16
    padding: (20, 0)

# Vertical light grey separator
<Vseparator@Widget>:
    size_hint_x: None
    width: 3
    canvas:
        Color:
            rgb: .5, .5, .5
        Rectangle:
            pos: self.center_x, -5
            size: .3, self.height

<LightBox@BoxLayout>:
    height: 40
    orientation: "horizontal"
    size_hint_y: None
    padding: 10
    canvas.before:
        Color:
            rgba: (.2, .2, .2, .8)
        Rectangle:
            pos: self.pos
            size: self.size

<DarkBox@BoxLayout>:
    height: 60
    orientation: "horizontal"
    size_hint_y: None
    padding: 10

<Hseparator@Widget>:
    size_hint_y: None
    height: self.thickness + 2 * self.margin
    thickness: 1
    margin: 1
    canvas:
        Color:
            rgb: .5, .5, .5
        Rectangle:
            pos: self.x + self.margin, self.y + self.margin +1
            size: self.width - 2 * self.margin, self.thickness

ShowcaseScreen:
    name: "Process"

    BoxLayout:
        orientation: "horizontal"

        ####
        #This will be the side selectors for conversion, filter, gcoder
        ####

        GridLayout:
            cols:1
            size_hint_x: .25
            padding: 10
            spacing: 10
            Sidebt:
                text: "Conversion\nConcatenation"
                state: "down"
                group: "process_panel"
                on_release: carousel.load_slide(carousel.slides[0])
            Sidebt:
                text: "Collapse"
                on_release: carousel.load_slide(carousel.slides[1])
                group: "process_panel"
            Sidebt:
                text: "Gcoder"
                on_release: carousel.load_slide(carousel.slides[2])
                group: "process_panel"
            Widget
            Button:
                size_hint_y: .30
                background_normal: "data/backgrounds/process_exec.png"
                background_down: "data/backgrounds/process_exec_down.png"
                text: "Execute"
                bold: True
                halign: "center"
                valign: "middle"
                text_size: self.size
                color: (0.2,0.2,0.2,1)
                on_release: app.process_exec()

        Vseparator

        # This will be the main screen with the options and stuff

        # The inclusion of the Carousel in the ScrollView is apparently
        # necessary. Otherwise, widgets in general will not respond as they
        # should to touch events
        ScrollView:
            size_hint_x: .75
            Carousel:
                id: carousel
                direction: "bottom"
                BoxLayout:
                    orientation: "vertical"

                    ScrollView:
                        size_hint_y: .85
                        bar_width: 4.5

                        GridLayout:
                            orientation: "vertical"
                            cols: 1
                            padding: 5
                            spacing: 5
                            height: root.height*2
                            size_hint_y: None
                            id: concatenation_slide

                            LightBox:
                                Label:
                                    markup: True
                                    text: "[size=15][b]General[/b][/size]"
                                    halign: "left"
                                    valign: "middle"
                                    color: [.85, .85, .85, 1]
                                    text_size: self.size

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]Concatenation[/b][/size]\n[size=13]Set on to perform concatenation of selected files. Otherwise it will convert[/size]"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Switch:
                                    id: concatenation
                                    size_hint_x: .2
                                    active: True
                                    on_active: if self.active is False: root.ids.conversion.disabled = True;
                                    on_active: if self.active is True: root.ids.conversion.disabled = False;

                            Hseparator

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]Output file[/b][/size]\n[size=13]Save output file to...[/size]"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Button:
                                    background_normal: "data/backgrounds/bt_process.png"
                                    size_hint_x: .2
                                    id: conversion
                                    shorten: True
                                    shorten_from: "right"
                                    text_size: self.size
                                    halign: "center"
                                    valign: "middle"
                                    bold: True
                                    text: "Select..."
                                    on_release: app.filechooser_dialog("conversion")

                            Hseparator

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]Output Format[/b][/size]\n[size=13]Choose the format of the output file(s). Multiple formats may be chosen[/size]"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Button:
                                    id: conv_formatbt
                                    background_normal: "data/backgrounds/bt_process.png"
                                    size_hint_x: .2
                                    bold: True
                                    text: "Fasta"
                                    on_release: app.format_dialog()

                            LightBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=15][b]Sequence filter options[/b][/size]"
                                    halign: "left"
                                    valign: "middle"
                                    color: [.85, .85, .85, 1]
                                    text_size: self.size
                                Switch:
                                    id: filter
                                    size_hint_x: .2
                                    on_active: if self.active == True: root.ids.cv_filterbt.disabled = False
                                    on_active: if self.active == False: root.ids.cv_filterbt.disabled = True

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    id: test2
                                    text: "[size=18][b]Gap/Missing data filter[/b][/size]\n[size=13] Set filters to remove alignment columns with excessive gap and/or missing data [/size]"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Button:
                                    id: cv_filterbt
                                    background_normal: "data/backgrounds/bt_process.png"
                                    size_hint_x: .2
                                    bold: True
                                    disabled: True
                                    text: "Set filters"
                                    on_release: app.filter_dialog()

                            LightBox:
                                Label:
                                    markup: True
                                    text: "[size=15][b]Partitioning options[/b][/size]"
                                    halign: "left"
                                    valign: "middle"
                                    color: [.85, .85, .85, 1]
                                    text_size: self.size

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    id: test2
                                    text: "[size=18][b]Reverse concatenation[/b][/size]\n[size=13]In case the active input file is concatenated, revert to individual files (In development) [/size]"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Switch:
                                    id: rev_concatenation
                                    size_hint_x: .2
                                    disabled: True

                            Hseparator

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    id: test2
                                    text: "[size=18][b]Partition file[/b][/size]\n[size=13]Provide the partitioning file either in nexus or RAxML like format [/size]"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Button:
                                    background_normal: "data/backgrounds/bt_process.png"
                                    size_hint_x: .2
                                    bold: True
                                    text: "Select..."
                                    disabled: True

                            LightBox:
                                Label:
                                    markup: True
                                    text: "[size=15][b]Formatting options[/b][/size]"
                                    halign: "left"
                                    valign: "middle"
                                    color: [.85, .85, .85, 1]
                                    text_size: self.size

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]Interleave[/b][/size]\n[size=13] If sequences should be in interleave format or leave"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Switch:
                                    id: interleave
                                    size_hint_x: .2
                                    disabled: True

                            Hseparator

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]Zorro support[/b][/size]\n[size=13] If concatenating, also concatenate auxiliary Zorro weight files. In development."
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Switch:
                                    id: zorro
                                    size_hint_x: .2
                                    disabled: True

                            Hseparator

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]Substitution model[/b][/size]\n[size=13] Specify the substitution model. Only supported for Nexus and Phylip formats"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Switch:
                                    size_hint_x: .2
                                    disabled: True

                            LightBox:
                                Label:
                                    markup: True
                                    text: "[size=15][b]Special options[/b][/size]"
                                    halign: "left"
                                    valign: "middle"
                                    color: [.85, .85, .85, 1]
                                    text_size: self.size

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]IMa2 [/b][/size]\n[size=13] Additional options for IMa2 format"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Button:
                                    background_normal: "data/backgrounds/bt_process.png"
                                    size_hint_x: .2
                                    text: "TOUCH ME!"
                                    on_press: self.text = "XUPEXA!"
                                    on_release: self.text = "TOUCH ME!"

                            Hseparator

                BoxLayout:
                    orientation: "vertical"

                    ScrollView:
                        size_hint_y: .85

                        GridLayout:
                            orientation: "vertical"
                            cols: 1
                            padding: 5
                            spacing: 5
                            height: root.height
                            size_hint_y: None

                            LightBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=15][b]Activate sequence collapsing[/b][/size]"
                                    halign: "left"
                                    valign: "middle"
                                    color: [.85, .85, .85, 1]
                                    text_size: self.size
                                Switch:
                                    size_hint_x: .2
                                    on_active: if self.active == True: root.ids.col_outputbt.disabled = False; root.ids.col_hapbt.disabled = False
                                    on_active: if self.active == False: root.ids.col_outputbt.disabled = True; root.ids.col_hapbt.disabled = True

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]Output file[/b][/size]\n[size=13]Save output file of collapse procedures[/size]"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Button:
                                    id: col_outputbt
                                    background_normal: "data/backgrounds/bt_process.png"
                                    size_hint_x: .2
                                    bold: True
                                    disabled: True
                                    text: "Select..."

                            LightBox:
                                Label:
                                    markup: True
                                    text: "[size=15][b]General[/b][/size]"
                                    halign: "left"
                                    valign: "middle"
                                    color: [.85, .85, .85, 1]
                                    text_size: self.size

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]Haplotype prefix[/b][/size]\n[size=13]Select the prefix name for the haplotypes[/size]"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Button:
                                    id: col_hapbt
                                    background_normal: "data/backgrounds/bt_process.png"
                                    size_hint_x: .2
                                    bold: True
                                    disabled: True
                                    text: "Select..."

                BoxLayout:
                    orientation: "vertical"

                    ScrollView:
                        size_hint_y: .85

                        GridLayout:
                            orientation: "vertical"
                            cols: 1
                            padding: 5
                            spacing: 5
                            height: root.height
                            size_hint_y: None

                            LightBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=15][b]Activate gap coding [/b][/size]"
                                    halign: "left"
                                    valign: "middle"
                                    color: [.85, .85, .85, 1]
                                    text_size: self.size
                                Switch:
                                    size_hint_x: .2
                                    on_active: if self.active == True: root.ids.cm_outputbt.disabled = False
                                    on_active: if self.active == False: root.ids.cm_outputbt.disabled = True

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]Output file[/b][/size]\n[size=13]Save output file to gap coding procedures[/size]"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Button:
                                    id: cm_outputbt
                                    background_normal: "data/backgrounds/bt_process.png"
                                    size_hint_x: .2
                                    bold: True
                                    disabled: True
                                    text: "Select..."

                            LightBox:
                                Label:
                                    markup: True
                                    text: "[size=15][b]General[/b][/size]"
                                    halign: "left"
                                    valign: "middle"
                                    color: [.85, .85, .85, 1]
                                    text_size: self.size

                            DarkBox:
                                Label:
                                    size_hint_x: .8
                                    markup: True
                                    text: "[size=18][b]Coding method[/b][/size]\n[size=13]Select the gap coding method[/size]"
                                    halign: "left"
                                    valign: "middle"
                                    text_size: self.size
                                Button:
                                    id: cm_methodbt
                                    background_normal: "data/backgrounds/bt_process.png"
                                    size_hint_x: .2
                                    bold: True
                                    disabled: True
                                    text: "Select..."