ShowcaseScreen:
    name: "Statistics"
    __safe_id: [taxa_dropdown.__self__, file_dropdown.__self__]
    orientation: "vertical"

    BoxLayout:
        AnchorLayout:
            id: sidepanel_container
            anchor_x: "left"
            size_hint_x: None
            width: 430
            ScrollView:
                size_hint_x: None
                width: 400
                size_hint_y: .9
                id: stats_panel
                BoxLayout:
                    id: stat_bx
                    orientation: "vertical"
                    padding: 10
                    spacing: 5
                    canvas.before:
                        Color:
                            rgb: (.2, .2, .2)
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    StackLayout:
                        size_hint_y: None
                        height: 2
                        canvas.after:
                            Color:
                                rgb: (0.216, 0.67, 0.784, 1)
                            Rectangle:
                                pos: 0, stats_panel.height - 2
                                size: stats_panel.width, 2
                    Label:
                        size_hint_y: None
                        height: 30
                        text: "Data exploration analyses"
                        bold: True
                        font_size: 18
                        color: (0.216, 0.67, 0.784, 1)
                    Widget:
                        size_hint_y: None
                        height: 5
                    ScrollView:
                        GridLayout:
                            id: main_stats_opts
                            padding: 5
                            spacing: 5
                            cols: 1
                            size_hint_y: None
                            height: sum([x.height for x in self.children])

                            TFStatsButton:
                                text: "General information"
                                on_release:
                                    app.toggle_data_options(self, self.text)

                            OptsGrid:
                                id: general_information
                                grid_name: "General information"

                            TFStatsButton:
                                text: "Polymorphism and Variation"
                                on_release:
                                    app.toggle_data_options(self, self.text)

                            OptsGrid:
                                id: polymorphism_data_opts
                                grid_name: "Polymorphism and Variation"

                            TFStatsButton:
                                text: "Missing Data"
                                on_release:
                                    app.toggle_data_options(self, self.text)

                            OptsGrid:
                                id: missing_data_opts
                                grid_name: "Missing Data"

                            TFStatsButton:
                                text: "Phylogenetic Tree Annotation"

                            OptsGrid:
                                id: tree_data_opts
                                grid_name: "Phylogenetic Tree Annotation"
                    Hseparator
                    BoxLayout:
                        orientation: "vertical"
                        size_hint_y: None
                        height: 65
                        spacing: 5
                        Label:
                            bold: True
                            text: "Select data set"
                            size_hint_y: None
                            height: 30
                        BoxLayout:
                            size_hint_y: None
                            height: 30
                            spacing: 10
                            ProcessBt:
                                id: active_file_set
                                text: "Active files"
                                on_release: app.statistics_populate_groups("files"); file_dropdown.open(self)

                            ProcessBt:
                                id: active_taxa_set
                                text: "Active taxa"
                                on_release: app.statistics_populate_groups("taxa"); taxa_dropdown.open(self)

                            DropDown:
                                id: taxa_dropdown
                                on_select: active_taxa_set.text = args[1]
                                canvas.before:
                                    Color:
                                        rgba: (0,0,0,1)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                                Button:
                                    background_normal: "data/backgrounds/spinner_opt.png"
                                    text: 'All taxa'
                                    size_hint_y: None
                                    height: 40
                                    bold: True
                                    on_release: taxa_dropdown.select(self.text)

                                Button:
                                    background_normal: "data/backgrounds/spinner_opt.png"
                                    text: 'Active taxa'
                                    size_hint_y: None
                                    height: 40
                                    bold: True
                                    on_release: taxa_dropdown.select(self.text)

                            DropDown:
                                id: file_dropdown
                                on_select: active_file_set.text = args[1]
                                canvas.before:
                                    Color:
                                        rgba: (0,0,0,1)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                                Button:
                                    background_normal: "data/backgrounds/spinner_opt.png"
                                    text: 'All files'
                                    size_hint_y: None
                                    height: 40
                                    bold: True
                                    on_release: file_dropdown.select(self.text)

                                Button:
                                    background_normal: "data/backgrounds/spinner_opt.png"
                                    text: 'Active files'
                                    size_hint_y: None
                                    height: 40
                                    bold: True
                                    on_release: file_dropdown.select(self.text)

        FloatLayout:
            size_hint_x: None
            Button:
                size_hint: None, None
                size: 40, 40
                border: 0,0,0,0
                pos_x_exp: 400
                pos: stats_panel.width, stats_panel.top - self.height
                background_normal: "data/backgrounds/tg_add_down.png" if self.pos[0] == self.pos_x_exp else "data/backgrounds/tg_remove_down.png"
                on_release:
                    app.toggle_stats_panel()

        ScrollView:
            scroll_timeout: 0
            ScatterLayout:
                id: plot_content
                auto_bring_to_front: False
                do_rotation: False
                Label:
                    valign: "middle"
                    halign: "center"
                    text_size: self.size
                    markup: True
                    bold: True
                    color: .7, .7, .7, .7
                    text: "[size=34]No data to display[/size]\nPlease select an analysis from the left panel"

    BoxLayout:
        size_hint_y: None
        height: 35
        spacing: 15
        canvas.before:
            Color:
                rgba: .2, .2, .2, .5
            Rectangle:
                pos: self.pos
                size: self.size
        Widget:
            size_hint_x: None
            width: 5
        Label:
            size_hint_x: None
            width: 120
            halign: "left"
            valign: "middle"
            text_size: self.size
            markup: True
            text: "Genes: [color=37abc8ff]N/A[/color]"
            bold: True
            id: gene_num
        Vseparator:
        Label:
            size_hint_x: None
            width: 120
            halign: "left"
            valign: "middle"
            text_size: self.size
            markup: True
            text: "Taxa: [color=37abc8ff]N/A[/color]"
            bold: True
            id: taxa_num
        Vseparator
        BoxLayout:
            id: footer_box


