ShowcaseScreen:
    name: "Statistics"

    BoxLayout:
        AnchorLayout:
            id: sidepanel_container
            anchor_x: "left"
            size_hint_x: None
            width: 330
            ScrollView:
                size_hint_x: None
                width: 300
                size_hint_y: .9
                id: stats_panel
                BoxLayout:
                    id: stat_bx
                    orientation: "vertical"
                    padding: 10
                    spacing: 5
                    canvas.before:
                        Color:
                            rgb: (.2, .2, .2)
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    StackLayout:
                        size_hint_y: None
                        height: 2
                        canvas.after:
                            Color:
                                rgb: (0.216, 0.67, 0.784, 1)
                            Rectangle:
                                pos: 0, stats_panel.height - 2
                                size: stats_panel.width, 2
                    Label:
                        size_hint_y: None
                        height: 30
                        text: "Data exploration analyses"
                        bold: True
                        font_size: 18
                        color: (0.216, 0.67, 0.784, 1)
                    Widget:
                        size_hint_y: None
                        height: 5
                    ScrollView:
                        GridLayout:
                            id: main_stats_opts
                            padding: 5
                            spacing: 5
                            cols: 1
                            size_hint_y: None
                            height: sum([x.height + 5 for x in self.children])
                            TFButton:
                                text: "Polymorphism and Variation"
                                height: 45
                                size_hint_y: None
                                on_release:
                                    app.toggle_data_options(self.text)

                            OptsGrid:
                                id: polymorphism_data_opts
                                grid_name: "Polymorphism and Variation"

                            TFButton:
                                text: "Missing Data"
                                height: 45
                                size_hint_y: None
                                on_release:
                                    app.toggle_data_options(self.text)

                            OptsGrid:
                                id: missing_data_opts
                                grid_name: "Missing Data"

                            TFButton:
                                text: "Phylogenetic Tree Annotation"
                                height: 45
                                size_hint_y: None

                            OptsGrid:
                                id: tree_data_opts
                                grid_name: "Phylogenetic Tree Annotation"
        FloatLayout:
            size_hint_x: None
            Button:
                size_hint: None, None
                size: 40, 40
                border: 0,0,0,0
                pos_x_exp: 300
                pos: stats_panel.width, stats_panel.height * .9 + self.height + 11
                background_normal: "data/backgrounds/tg_add_down.png" if self.pos[0] == self.pos_x_exp else "data/backgrounds/tg_remove_down.png"
                on_release:
                    app.toggle_stats_panel()

        ScrollView:
            scroll_timeout: 0
            ScatterLayout:
                id: plot_content
                auto_bring_to_front: False
                do_rotation: False
                Label:
                    text: "Some text verrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrry long text"
