ShowcaseScreen:
    name: "main"

    # The initial home screen could be a FloatLayout that contains drawn
    # arrows and text (images) with information on what each button does

    BoxLayout:
        orientation: "vertical"
        padding: [50,30,0, 0]
        BoxLayout:
            size_hint_y: None
            height: 120
            spacing: 25
            AnchorLayout:
                size_hint_x: None
                width: 100
                Image:
                    size_hint: None, None
                    size: 100, 100
                    source: "data/backgrounds/trifusion_bw.png"
            Label:
                markup: True
                color: .7, .7, .7, .7
                bold: True
                valign: "middle"
                halign: "left"
                text_size: self.size
                text: "[size=40]Welcome to TriFusion[/size]\n[size=20]Streamlining phylogenomic data gathering, processing and visualization[/size]\n\nStart by clicking '[color=37abc8ff]Menu > Open file(s)[/color]', by typing '[color=37abc8ff]Ctrl + O[/color]' or simply [color=37abc8ff]drag and drop[/color] your files into TriFusion's window"

        AnchorLayout:
            anchor_x: "center"
            anchor_y: "center"
            BoxLayout:
                size_hint: None, None
                size: 450,350
                orientation: "vertical"
                id: project_bx
                StackLayout:
                    size_hint_y: None
                    height: 0
                    canvas.after:
                        Color:
                            rgba: (0.216, 0.67, 0.784, 1)
                        Line:
                            width: 1.1
                            cap: "round"
                            joint: "round"
                            rectangle: project_bx.x,project_bx.y,project_bx.width,project_bx.height
                BoxLayout:
                    size_hint_y: None
                    height: 40
                    canvas.before:
                        Color:
                            rgba: (0.216, 0.67, 0.784, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    Label:
                        markup: True
                        text: "Quick Open Project"
                        bold: True
                        font_size: 20

                ScrollView:
                    scroll_type: ["bars"]
                    bar_width: 8
                    scroll_timeout: 1000
                    bar_pos_x: "top"
                    bar_pos_y: "right"

                    GridLayout:
                        cols: 3
                        padding: 20
                        spacing: 5, 5
                        size_hint_y: None
                        height: self.minimum_height
                        id: home_projects_grid
                        Button:
                            disabled: True
                            text: "No saved projects"
                            bold: True
                            size_hint_y: None
                            height: 50

                Hseparator:
                    thickness: 1.5

                Widget:
                    size_hint_y: None
                    height: 5

                BoxLayout:
                    size_hint_y: None
                    height: 45
                    padding: 10

                    ProjectOrtoBt

                    Label:
                        bold: True
                        font_size: 16
                        halign: "center"
                        valign: "top"
                        text_size: self.size
                        text: "Orthology project"

                    ProjectProcBt

                    Label:
                        bold: True
                        font_size: 16
                        halign: "center"
                        valign: "top"
                        text_size: self.size
                        text: "Process project"

#        BoxLayout:
#            BoxLayout:
#                padding: 10
#                id: orto_overview
#                orientation: "vertical"
#                size_hint_y: .7
#                StackLayout:
#                    size_hint_y: None
#                    height: 0
#                    canvas.after:
#                        Color:
#                            rgb: (211/255, 70/255, 70/255, 1)
#                        Line:
#                            width: 0.8
#                            cap: "round"
#                            joint: "round"
#                            rectangle: orto_overview.x,orto_overview.y,orto_overview.width,orto_overview.height
#                Label:
#                    markup: True
#                    bold: True
#                    size_hint_y: None
#                    height: 35
#                    text: "[size=30]Orthology[/size]"
#                    halign: "left"
#                    valign: "middle"
#                    text_size: self.size
#                    color: (211/255, 70/255, 70/255, 1)
#                Widget
#            BoxLayout:
#        BoxLayout:
#            id: process_overview
#            StackLayout:
#                canvas.after:
#                    Color:
#                        rgb: (0, 84/255, 210/255, 1)
#                    Line:
#                        width: 0.8
#                        cap: "round"
#                        joint: "round"
#                        rectangle: process_overview.x,process_overview.y,process_overview.width,process_overview.height
#        BoxLayout:
#            id: stats_overview
#            StackLayout:
#                canvas.after:
#                    Color:
#                        rgb: (111/255, 179/255, 49/255, 1)
#                    Line:
#                        width: 0.8
#                        cap: "round"
#                        joint: "round"
#                        rectangle: stats_overview.x,stats_overview.y,stats_overview.width,stats_overview.height


