#:import StatsSummary trifusion.data.resources.custom_widgets.StatsSummary
#:import GeneTable trifusion.data.resources.custom_widgets.GeneTable
#:import tm trifusion.data.resources.theme.default

ShowcaseScreen:
    name: "Statistics"
    orientation: "vertical"

    BoxLayout:
        AnchorLayout:
            id: sidepanel_container
            anchor_x: "left"
            size_hint_x: None
            width: 470
            ScrollView:
                size_hint_x: None
                width: 410
                size_hint_y: .9
                id: stats_panel
                BoxLayout:
                    id: stat_bx
                    orientation: "vertical"
                    padding: 10
                    spacing: 5
                    canvas.before:
                        Color:
                            rgba: tm.c_stats_sidepanel
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    StackLayout:
                        size_hint_y: None
                        height: 0
                        canvas.after:
                            Color:
                                rgb: (0.216, 0.67, 0.784, 1)
                            Line:
                                width: 1.5
                                points: [0, stats_panel.height, stats_panel.width, stats_panel.height]
                    Label:
                        size_hint_y: None
                        height: 30
                        text: "Data exploration analyses"
                        bold: True
                        font_size: 18
                        color: (0.216, 0.67, 0.784, 1)
                    Widget:
                        size_hint_y: None
                        height: 5
                    ScrollView:
                        bar_width: 10
                        scroll_type: ["bars"]
                        GridLayout:
                            id: main_stats_opts
                            padding: [5, 5, 15, 5]
                            spacing: 5
                            cols: 1
                            size_hint_y: None
                            height: self.minimum_height

                            TFStatsButton:
                                text: "General information"
                                on_release:
                                    app.toggle_stats_options(self, self.text)

                            OptsGrid:
                                id: general_information
                                grid_name: "General information"

                            TFStatsButton:
                                text: "Polymorphism and Variation"
                                on_release:
                                    app.toggle_stats_options(self, self.text)

                            OptsGrid:
                                id: polymorphism_data_opts
                                grid_name: "Polymorphism and Variation"

                            TFStatsButton:
                                text: "Missing Data"
                                on_release:
                                    app.toggle_stats_options(self, self.text)

                            OptsGrid:
                                id: missing_data_opts
                                grid_name: "Missing Data"

                            TFStatsButton:
                                text: "Outlier detection"
                                on_release:
                                    app.toggle_stats_options(self, self.text)

                            OptsGrid:
                                id: outlier_opts
                                grid_name: "Outlier detection"

                            #TFStatsButton:
                            #    text: "Phylogenetic Tree Annotation"

                            #OptsGrid:
                            #    id: tree_data_opts
                            #    grid_name: "Phylogenetic Tree Annotation"

                    Hseparator
                    BoxLayout:
                        orientation: "vertical"
                        size_hint_y: None
                        height: 65
                        spacing: 5
                        Label:
                            bold: True
                            text: "Select data set"
                            size_hint_y: None
                            height: 30
                        BoxLayout:
                            size_hint_y: None
                            height: 30
                            spacing: 10
                            BoxLayout:
                                spacing: 10
                                ProcessBt:
                                    id: active_file_set
                                    text: "Active files"
                                    on_release: app.toggle_fancy_dropdown(self, sorted(app.file_groups), orientation="up", add_ds_type="files")

                                ProcessBt:
                                    id: active_taxa_set
                                    text: "Active taxa"
                                    on_release: app.toggle_fancy_dropdown(self, sorted(app.taxa_groups), orientation="up", add_ds_type="taxa")
                            Button:
                                size_hint: None, None
                                size: 30, 30
                                border: 0,0,0,0
                                background_normal: "data/backgrounds/refresh_bt.png"
                                background_down: "data/backgrounds/refresh_bt.png"
                                on_release:
                                    if isinstance(plot_content.children[0].children[0], StatsSummary) or isinstance(plot_content.children[0].children[0], GeneTable):\
                                    app.statistics_show_summary()
                                    elif app.current_plt_idx:\
                                    app.stats_show_plot(*app.current_plt_idx)

        FloatLayout:
            size_hint_x: None
            width: 0
            Button:
                size_hint: None, None
                size: 40, 40
                border: 0,0,0,0
                pos_x_exp: 410
                pos: stats_panel.width, stats_panel.top - self.height
                background_normal: "data/backgrounds/tg_add_down.png" if self.pos[0] == self.pos_x_exp else "data/backgrounds/tg_remove_down.png"
                background_down: "data/backgrounds/tg_add_down.png" if self.pos[0] == self.pos_x_exp else "data/backgrounds/tg_remove_down.png"
                on_release:
                    app.toggle_stats_panel()

        FloatLayout:
            size_hint_x: None
            width: 0
            TFButton:
                id: sum_stats_bt
                size_hint: None, None
                size: 40, 40
                border: 0,0,0,0
                pos: stats_panel.width, stats_panel.top - self.height - 45
                background_normal: "data/backgrounds/summary_stats.png"
                background_down: "data/backgrounds/summary_stats_down.png"
                on_release:
                    app.statistics_show_summary(force=True)

#        FloatLayout:
#            size_hint_x: None
#            width: 0
#
#            ScatterLayout:
#                size_hint: None, None
#                size: 230, 40
#                pos: stats_panel.width, stats_panel.top - self.width - 160
#                rotation: 90
#                TFButton:
#                    text: "Summary statistics overview"
#                    on_release:
#                        app.statistics_show_summary(force=True)


        ScrollView:
            scroll_timeout: 0
            ScatterLayout:
                id: plot_content
                auto_bring_to_front: False
                do_rotation: False
                Label:
                    valign: "middle"
                    halign: "center"
                    text_size: self.size
                    markup: True
                    bold: True
                    color: .7, .7, .7, .7
                    text: "[size=34]No data to display[/size]\nPlease select an analysis from the left panel"

    BoxLayout:
        size_hint_y: None
        height: 35
        spacing: 15
        canvas.before:
            Color:
                rgba: .2, .2, .2, .5
            Rectangle:
                pos: self.pos
                size: self.size
        Widget:
            size_hint_x: None
            width: 5
        Label:
            size_hint_x: None
            width: 120
            halign: "left"
            valign: "middle"
            text_size: self.size
            markup: True
            text: "Genes: [color=37abc8ff]N/A[/color]"
            bold: True
            id: gene_num
        Vseparator:
        Label:
            size_hint_x: None
            width: 120
            halign: "left"
            valign: "middle"
            text_size: self.size
            markup: True
            text: "Taxa: [color=37abc8ff]N/A[/color]"
            bold: True
            id: taxa_num
        Vseparator
        BoxLayout:
            id: footer_box


